import STCC.TopologicalProperties
import Mathlib.Order.WellFounded
import Mathlib.Topology.UrysohnsLemma

open BigOperators
namespace Chp5
open CellComplexClass

section
variable {X: Type*} [T: TopologicalSpace X] [T2Space X] [C: CellComplexClass X] [CW: CWComplexClass X]
-- a direct proof of 5.17
theorem quotient_sigma_cb_map : Topology.IsQuotientMap (fun (⟨e, d⟩: (_:C.sets) × cb (C.dim_map _)) ↦ C.characteristic_map e d) where
  surjective := by
    intro x
    simp
    rcases exists_mem_of_cell x with ⟨e, e_in_sets, x_in_e⟩
    use e, e_in_sets
    have : x ∈ Set.range (C.characteristic_map ⟨e, e_in_sets⟩) := by
      rw [characteristic_map_range]
      apply subset_closure
      exact x_in_e
    rw [Set.mem_range] at this
    rcases this with ⟨y, hy⟩
    use y.1, y.2
  eq_coinduced := by
    rw [TopologicalSpace.ext_iff]
    intro s
    let φ := fun (⟨e, d⟩: (_:C.sets) × cb (C.dim_map _)) ↦ C.characteristic_map e d
    show @IsOpen X T s ↔ @IsOpen X (TopologicalSpace.coinduced φ instTopologicalSpaceSigma) s
    have : @IsOpen X (TopologicalSpace.coinduced φ instTopologicalSpaceSigma) s ↔ IsOpen (φ ⁻¹' s) := by rfl
    rw [this, isOpen_sigma_iff]
    simp only [Set.preimage_preimage, φ]
    refine Iff.intro ?mp ?mpr
    case mp =>
      intro s_open_in_X e
      apply Continuous.isOpen_preimage ?_ s s_open_in_X
      exact characteristic_map_continuous e
    case mpr=>
      intro h
      rw [CW.coeherent.open_crit]
      rintro _ ⟨e, e_in_sets, rfl⟩
      let f : cb (C.dim_map ⟨e, e_in_sets⟩) → (closure e) := by
        intro d
        use C.characteristic_map ⟨e, e_in_sets⟩ d
        show characteristic_map ⟨e, e_in_sets⟩ d ∈ closure (⟨e, e_in_sets⟩:C.sets).1
        rw [←characteristic_map_range]
        exact Set.mem_range_self d
      let g : (closure e) → X := (↑)
      have f_cont: Continuous f := by
        -- this refine is generated by apply?
        refine
          Continuous.subtype_mk ?_ fun x ↦
            id
              (Eq.mpr
                (id
                  (congrArg (fun _a ↦ characteristic_map ⟨e, e_in_sets⟩ x ∈ _a)
                    (Eq.symm (characteristic_map_range ⟨e, e_in_sets⟩))))
                (Set.mem_range_self x))
        exact characteristic_map_continuous ⟨e, e_in_sets⟩
      have : Topology.IsQuotientMap f := by
        apply IsClosedMap.isQuotientMap (Continuous.isClosedMap f_cont) f_cont
        rintro ⟨x, x_in_ce⟩
        simp [f]
        rw [←characteristic_map_range' e e_in_sets, Set.mem_range] at x_in_ce
        rcases x_in_ce with ⟨y, hy⟩
        use y.1, y.2
      rw [←Topology.IsQuotientMap.isOpen_preimage this]
      rw [Set.preimage_preimage]
      apply h

def CellAttached_boundary {n: ℕ} {ι: Type*} : Set (Σ_: ι, cb n) := {x | x.2 ∈ cb_boundary}

def CellAttached_f {n: ℕ} {ι: Type*} {S: Set X} (g: ι → cb n → X) (hg: ∀ i:ι, ∀ x:cb n, x ∈ cb_boundary →  g i x ∈ S) : @CellAttached_boundary n ι → S := fun x ↦ ⟨g x.1.1 x.1.2, hg x.1.1 x.1.2 x.2⟩

def CellAttached {n: ℕ} {ι: Type*} {S: Set X} (g: ι → cb n → X) (hg: ∀ i:ι, ∀ x:cb n, x ∈ cb_boundary →  g i x ∈ S) :=
  AdjointSpace CellAttached_boundary (CellAttached_f g hg)

instance {n: ℕ} {ι: Type*} {S: Set X} (g: ι → cb n → X) (hg: ∀ i:ι, ∀ x:cb n, x ∈ cb_boundary →  g i x ∈ S) : TopologicalSpace (CellAttached g hg)  := by
  rw [CellAttached]
  infer_instance

def CellOfDim (n: ℕ) := {e: C.sets | C.dim_map e = n}

def characteristic_cn (n: ℕ) : @CellOfDim X _ _ C n → cb n → X := fun ⟨e, he⟩ x ↦ C.characteristic_map e ((congrArg (fun p ↦ (cb p: Type)) he.symm).mp x)

-- example usage of Eq.rec and congArg
-- example {f : ℕ → Type} (n1 n2: ℕ) (h: n1 = n2) : f n1 = f n2 := by
--   exact congrArg f h
-- example {f: ℕ → Type} {g: (n: ℕ) → Set (f n)}{n1 n2: ℕ} (eq: n1 + 1 = n2) (x: f (n1 + 1)) (h: x ∈ g (n1 + 1)): (congrArg f eq).mp x ∈ g n2 :=
--   Eq.rec (motive := fun n2' eq' => (congrArg f eq').mp x ∈ g n2') h eq

omit CW in theorem char_cnp1_boundary_in_skn (n: ℕ): ∀ e: CellOfDim (n + 1), ∀ x: (cb (n + 1)), x ∈ cb_boundary → (characteristic_cn (n + 1) e x) ∈ Skeleton X n := by
  rintro ⟨e, he⟩ x x_in_boundary
  have mem_0: characteristic_cn (n + 1) ⟨e, he⟩ x ∈ Set.range (cb_boundary_map (C.characteristic_map e)) := by
    rw [characteristic_cn]
    apply mem_boundary_map_range_of_mem_boundary
    apply @Eq.rec ℕ (n + 1) (fun (n':ℕ) (eq:(n + 1 = n')) ↦ (congrArg (fun p ↦ (cb p:Type)) eq.symm).mpr x ∈ @cb_boundary n') x_in_boundary _ (he.symm)
  have mem_1: Set.range (cb_boundary_map (C.characteristic_map e)) ⊆ ⋃p:sets, ⋃_:(C.dim_map p < C.dim_map e), p.1 := C.characteristic_map_boundary e
  have mem_2: ⋃p:sets, ⋃_:(C.dim_map p < C.dim_map e), p.1 ⊆ Skeleton X n := by
    rw [Set.iUnion₂_subset_iff]
    intro p hp
    rw [he] at hp
    rw [sub_skeleton_iff, Nat.le_iff_lt_add_one]
    exact hp
  exact mem_2 (mem_1 mem_0)

def skn_sum_cnp1_to_sknp1 (n: ℕ): (Skeleton X n) ⊕ (Σ_:@CellOfDim X _ _ C (n + 1), cb (n + 1)) → (Skeleton X (n + 1)) := by
  intro x
  match x with
  | Sum.inl ⟨x, x_in_Xn⟩ =>
    exact ⟨x, skeleton_mono n (n + 1) (Nat.le_add_right n 1) x_in_Xn⟩
  | Sum.inr ⟨⟨e, he⟩, x⟩ =>
    use C.characteristic_map e ((congrArg (fun p ↦ (cb p : Type)) he).mpr x)
    suffices Set.range (C.characteristic_map e) ⊆ (Skeleton X (n + 1)) by exact this (Set.mem_range_self _)
    rw [characteristic_map_range]
    apply (Skeleton X (n + 1)).cell_closure_incl e.1 e.2
    show e.1 ⊆ Skeleton X (n + 1)
    rw [sub_skeleton_iff, he]

omit CW in theorem skn_sum_cnp1_to_sknp1_surj {n: ℕ}: Function.Surjective (skn_sum_cnp1_to_sknp1 (C := C) n) := by
  intro x
  rcases exists_mem_of_cell (x:X) with ⟨e, e_in_sets, x_in_e⟩
  have : C.dim_map ⟨e, e_in_sets⟩ ≤ (n + 1) := by
    rw [←sub_skeleton_iff]
    simp
    apply (Skeleton X (n + 1)).subset_of_intersect e_in_sets
    rw [←Set.nonempty_iff_ne_empty]
    use x
    exact ⟨x_in_e, x.2⟩
  match Nat.le_succ_iff.mp this with
  | Or.inl dim_e_le_n =>
    have: (x:X) ∈ (Skeleton X n) := by
      suffices e ⊆ (Skeleton X n) by
        exact this x_in_e
      show (⟨e, e_in_sets⟩:C.sets).1 ⊆ (Skeleton X n)
      rwa [sub_skeleton_iff]
    use Sum.inl ⟨x, this⟩
    rfl
  | Or.inr dim_e_eq_np1 =>
    let e': C.sets := ⟨e, e_in_sets⟩
    have : (x:X) ∈ e'.1 := x_in_e
    rw [←characteristic_map_inner_image] at this
    rcases this with ⟨y, y_in_inner, y_map_to_x⟩
    let f := (congrArg (fun p ↦ (cb p: Type)) dim_e_eq_np1).mp
    let g := (congrArg (fun p ↦ (cb p: Type)) dim_e_eq_np1).mpr
    let y': cb (n + 1) := (congrArg (fun p ↦ (cb p: Type)) dim_e_eq_np1).mp y
    use Sum.inr ⟨⟨e', dim_e_eq_np1⟩, y'⟩
    simp [skn_sum_cnp1_to_sknp1]
    apply SetCoe.ext;simp
    show C.characteristic_map e' (g y') = x
    have : g (f y) = y := by simp [f, g]
    rwa [this]

omit CW in theorem skn_sum_cnp1_to_sknp1_cont {n: ℕ}: Continuous (skn_sum_cnp1_to_sknp1 (C:= C) n) := by
  rw [continuous_sum_dom]
  refine And.intro ?inl_cont ?inr_cont
  case inl_cont =>
    have : skn_sum_cnp1_to_sknp1 n ∘ Sum.inl = fun x ↦ ⟨x.1, skeleton_mono (C:=C) n (n + 1) (Nat.le_add_right n 1) x.2⟩ := by
      ext x
      simp [skn_sum_cnp1_to_sknp1]
    rw [this]
    exact Continuous.subtype_mk continuous_subtype_val fun x ↦ skeleton_mono n (n + 1) (Nat.le_add_right n 1) x.property
  case inr_cont =>
    apply continuous_sigma
    intro e
    simp [skn_sum_cnp1_to_sknp1]
    apply Continuous.subtype_mk
    apply Continuous.comp
    . apply C.characteristic_map_continuous
    exact @Eq.rec ℕ (C.dim_map e.1) (fun n hn ↦ Continuous (congrArg (fun p ↦ (cb p : Type)) hn).mpr) (continuous_id) (n + 1) e.2

omit CW in theorem skn_sum_cnp1_to_sknp1_factors {n: ℕ}: ∀ x₁ x₂: (Skeleton X n) ⊕ (Σ_:CellOfDim (n + 1), cb (n + 1)),
  glue_setoid
    (@CellAttached_boundary (n + 1) (CellOfDim (n + 1)))
    (@CellAttached_f X (n + 1) (CellOfDim (n + 1)) (Skeleton X n) (characteristic_cn (n + 1)) (char_cnp1_boundary_in_skn n))
    x₁ x₂ →
  skn_sum_cnp1_to_sknp1 n x₁ = skn_sum_cnp1_to_sknp1 n x₂ := by
    intro x₁ x₂ h₁₂
    rcases glue_rel_equiv_explicit _ _ x₁ x₂ h₁₂ with c0 | c1 | c2 | c3 | c4
    . rcases c0 with ⟨x, heq1, heq2⟩
      rw [heq2]
    . rcases c1 with ⟨x, y, y', heq1, heq2, heq3, heq4⟩
      rw [CellAttached_f] at heq4
      simp [heq1, skn_sum_cnp1_to_sknp1, heq2, heq4, ←heq3, characteristic_cn]
      rw [←heq3]
    . rcases c2 with ⟨y, x, y', heq1, heq2, heq3, heq4⟩
      rw [CellAttached_f] at heq4
      simp [heq1, skn_sum_cnp1_to_sknp1, heq2, heq4, ←heq3, characteristic_cn]
      rw [←heq3]
    . rcases c3 with ⟨y₁, y₂, y₁', y₂', heq1, heq2, heq3, heq4, heq5, hne⟩
      simp [heq1, heq2, skn_sum_cnp1_to_sknp1]
      simp [CellAttached_f, characteristic_cn, heq3, heq4] at heq5
      rwa [heq3, heq4] at heq5
    . rcases c4 with ⟨y, heq1, heq2⟩
      rw [heq2]

def cell_attached_to_sknp1 (n: ℕ): @CellAttached X (n + 1) _ _ (characteristic_cn (n + 1)) (char_cnp1_boundary_in_skn n) → (Skeleton X (n + 1)) := (Quotient.lift (skn_sum_cnp1_to_sknp1 n) skn_sum_cnp1_to_sknp1_factors)

section helper
variable {X: Type*} [T: TopologicalSpace X] [T2Space X] [C: CellComplexClass X]
theorem mem_boundary_of_same_char_image₁ {n: ℕ} {y₁ y₂: cb (n + 1)} {e₁ e₂: C.sets} (h_e₁_dim: C.dim_map e₁ = n + 1)
    (h_e₂_dim: C.dim_map e₂ = n + 1) (h_ne_y: y₁ ≠ y₂) (e₁_eq_e₂: e₁ = e₂)
    (h_img_eq: C.characteristic_map e₁ ((congrArg (fun p ↦ (cb p : Type)) h_e₁_dim.symm).mp y₁) =
        C.characteristic_map e₂ ((congrArg (fun p ↦ (cb p : Type)) h_e₂_dim.symm).mp y₂)):
    y₁ ∈ cb_boundary ∧ y₂ ∈ cb_boundary := by
        have h_img_eq': C.characteristic_map e₁ ((congrArg (fun p ↦ (cb p : Type)) h_e₁_dim.symm).mp y₁) =
            C.characteristic_map e₁ ((congrArg (fun p ↦ (cb p : Type)) h_e₁_dim.symm).mp y₂) := by
                rw [h_img_eq]
                apply @Eq.rec C.sets e₁
                    (fun (e':C.sets) (h: e₁ = e') ↦
                        C.characteristic_map e' ((congrArg (fun p ↦ (cb p:Type)) ((congrArg C.dim_map h).symm.trans h_e₁_dim).symm).mp y₂) =
                            C.characteristic_map e₁ ((congrArg (fun p ↦ (cb p : Type)) h_e₁_dim.symm).mp y₂))
                    rfl
                exact e₁_eq_e₂
        let f : cb (n + 1) → cb (C.dim_map e₁) := (congrArg (fun p ↦ (cb p : Type)) h_e₁_dim.symm).mp
        let g : cb (C.dim_map e₁) → cb (n + 1) := (congrArg (fun p ↦ (cb p : Type)) h_e₁_dim).mp
        have g_f_inv: ∀ y, g (f y) = y := by
            intro y
            simp [g, f]
        have f_y_in_inner: ∀ y:(cb (n + 1)), y ∈ cb_inner → f y ∈ cb_inner  := by
            intro y hy
            apply @Eq.rec ℕ (n + 1) (fun m hm ↦ (congrArg (fun p ↦ (cb p : Type)) hm).mp y ∈ cb_inner) hy
            exact h_e₁_dim.symm
        have f_y_in_boundary: ∀y:(cb (n + 1)), y ∈ cb_boundary → f y ∈ cb_boundary := by
            intro y hy
            apply @Eq.rec ℕ (n + 1) (fun m hm ↦ (congrArg (fun p ↦ (cb p : Type)) hm).mp y ∈ cb_boundary) hy
            exact h_e₁_dim.symm
        match @cb_decomp (n + 1) y₁ with
        | Or.inl y₁_in_inneer =>
            have f_y₁_in_inner : f y₁ ∈ cb_inner := f_y_in_inner y₁ y₁_in_inneer
            match @cb_decomp (n + 1) y₂ with
            | Or.inl y₂_in_inner =>
                -- try to get a contradiction
                have f_y₂_in_inner : f y₂ ∈ cb_inner := f_y_in_inner y₂ y₂_in_inner
                have : y₁ = y₂ := by
                    rw [←g_f_inv y₁, ←g_f_inv y₂]
                    apply congrArg
                    exact characteristic_map_inj_on_inner e₁ f_y₁_in_inner f_y₂_in_inner h_img_eq'
                contradiction
            | Or.inr y₂_in_boundary =>
                have f_y₂_in_boundary: f y₂ ∈ cb_boundary := f_y_in_boundary y₂ y₂_in_boundary
                have : C.characteristic_map e₁ (f y₁) ≠ C.characteristic_map e₁ (f y₂) := by
                    exact characteristic_map_inner_boundary_ne _ _ _ _ f_y₁_in_inner f_y₂_in_boundary rfl
                contradiction
        | Or.inr y₁_in_boundary =>
            have f_y₁_in_boundary: f y₁ ∈ cb_boundary := f_y_in_boundary y₁ y₁_in_boundary
            match @cb_decomp (n + 1) y₂ with
            | Or.inl y₂_in_inner =>
                have f_y₂_in_inner: f y₂ ∈ cb_inner := f_y_in_inner _ y₂_in_inner
                have: C.characteristic_map e₁ (f y₁) ≠ C.characteristic_map e₁ (f y₂) := by
                    apply Ne.symm
                    exact characteristic_map_inner_boundary_ne _ _ _ _ f_y₂_in_inner f_y₁_in_boundary rfl
                contradiction
            | Or.inr y₂_in_boundary =>
                exact ⟨y₁_in_boundary, y₂_in_boundary⟩

theorem mem_boundary_of_same_char_image₂ {n: ℕ} {y₁ y₂: cb (n + 1)} {e₁ e₂: C.sets} (h_e₁_dim: C.dim_map e₁ = n + 1)
    (h_e₂_dim: C.dim_map e₂ = n + 1) (e₁_ne_e₂: e₁ ≠ e₂)
    (h_img_eq: C.characteristic_map e₁ ((congrArg (fun p ↦ (cb p : Type)) h_e₁_dim.symm).mp y₁) =
        C.characteristic_map e₂ ((congrArg (fun p ↦ (cb p : Type)) h_e₂_dim.symm).mp y₂)):
    y₁ ∈ cb_boundary ∧ y₂ ∈ cb_boundary := by
      let ff : (e:C.sets) → (he: C.dim_map e = n + 1) → cb (n + 1) → cb (C.dim_map e) := fun e he ↦ (congrArg (fun p ↦ (cb p : Type)) he.symm).mp
      have ff_y_in_set: ∀ e:C.sets, ∀ he: (C.dim_map e = n + 1), ∀ sf: ((n:ℕ) → Set (cb n)), ∀ y:cb (n + 1), y ∈ sf (n + 1) → ff e he y ∈ sf (C.dim_map e) := by
        intro e he sf y hy
        apply @Eq.rec ℕ (n + 1) (fun m hm ↦ (congrArg (fun p ↦ (cb p : Type)) hm).mp y ∈ sf m) hy
        exact he.symm
      let y₁' := ff e₁ h_e₁_dim y₁
      let y₂' := ff e₂ h_e₂_dim y₂
      have h_img_eq' : C.characteristic_map e₁ y₁' = C.characteristic_map e₂ y₂' := h_img_eq
      match @cb_decomp (n + 1) y₁ with
      | Or.inl y₁_in_inner =>
        have ff_y₁_in_inner : y₁' ∈ cb_inner := ff_y_in_set e₁ h_e₁_dim @cb_inner y₁ y₁_in_inner
        have cff_y₁_in_e₁: C.characteristic_map e₁ y₁' ∈ e₁.1 := by rw [←characteristic_map_inner_image];use y₁'
        match @cb_decomp (n + 1) y₂ with
        | Or.inl y₂_in_inner =>
          have f_y₂_in_inner : y₂' ∈ cb_inner := ff_y_in_set e₂ h_e₂_dim @cb_inner y₂ y₂_in_inner
          have cff_y₂_in_e₂: C.characteristic_map e₂ y₂' ∈ e₂.1 := by rw [←characteristic_map_inner_image];use y₂'
          rw [←h_img_eq] at cff_y₂_in_e₂
          have : e₁ = e₂ := by
            apply SetCoe.ext
            exact same_cell_of_mem e₁.2 e₂.2 cff_y₁_in_e₁ cff_y₂_in_e₂
          contradiction
        | Or.inr y₂_in_boundary =>
          have ff_y₂_in_boundary : y₂' ∈ cb_boundary := ff_y_in_set e₂ h_e₂_dim @cb_boundary y₂ y₂_in_boundary
          have : C.characteristic_map e₁ y₁' ≠ C.characteristic_map e₂ y₂' := characteristic_map_inner_boundary_ne e₁ e₂ y₁' y₂' ff_y₁_in_inner ff_y₂_in_boundary (h_e₁_dim.trans h_e₂_dim.symm)
          contradiction
      | Or.inr y₁_in_boundary =>
        have ff_y₁_in_boundary : y₁' ∈ cb_boundary := ff_y_in_set e₁ h_e₁_dim @cb_boundary y₁ y₁_in_boundary
        match @cb_decomp (n + 1) y₂ with
        | Or.inl y₂_in_inner =>
          have ff_y₂_in_inner : y₂' ∈ cb_inner := ff_y_in_set e₂ h_e₂_dim @cb_inner y₂ y₂_in_inner
          have : C.characteristic_map e₁ y₁' ≠ C.characteristic_map e₂ y₂' := (characteristic_map_inner_boundary_ne e₂ e₁ y₂' y₁' ff_y₂_in_inner ff_y₁_in_boundary (h_e₂_dim.trans h_e₁_dim.symm)).symm
          contradiction
        | Or.inr y₂_in_boundary =>
          exact ⟨y₁_in_boundary, y₂_in_boundary⟩
end helper

theorem cell_attached_to_sknp1_homeomorphic {n: ℕ} : IsHomeomorph (@cell_attached_to_sknp1 X _ _ _ n) := by
  refine quotient_lift_is_homeomorph _ ?factors ?is_quot
  case factors =>
    intro x₁ x₂ hx₁x₂
    match x₁ with
    | Sum.inl xl₁ =>
      match x₂ with
      | Sum.inl xl₂ =>
        simp [skn_sum_cnp1_to_sknp1] at hx₁x₂
        rw [hx₁x₂]
      | Sum.inr xr₂ =>
        simp [skn_sum_cnp1_to_sknp1] at hx₁x₂
        have : xr₂ ∈ CellAttached_boundary := by
          apply @mem_boundary_of_image_in_skeleton X _ _ _ n xr₂.2 xr₂.1
          case hy => simp [←hx₁x₂]
          case h_e_dim => exact xr₂.1.2
        simp [glue_setoid]
        apply Relation.EqvGen.rel
        rw [glue_rel]
        use ⟨xr₂, this⟩
        simp [CellAttached_f, characteristic_cn, ←hx₁x₂]
    | Sum.inr xr₁ =>
      match x₂ with
      | Sum.inl xl₂ =>
        simp [skn_sum_cnp1_to_sknp1] at hx₁x₂
        simp [glue_setoid]
        apply Relation.EqvGen.symm
        apply Relation.EqvGen.rel
        rw [glue_rel]
        have: xr₁ ∈ CellAttached_boundary := by
          apply @mem_boundary_of_image_in_skeleton X _ _ _ n xr₁.2 xr₁.1
          case hy => simp [hx₁x₂]
          case h_e_dim => exact xr₁.1.2
        use ⟨xr₁, this⟩
        simp [CellAttached_f, characteristic_cn, hx₁x₂]
      | Sum.inr xr₂ =>
        rcases eq_or_ne xr₁ xr₂ with heq | hne
        . exact Quotient.eq''.mp (congrArg Quotient.mk'' (congrArg Sum.inr heq))
        simp [skn_sum_cnp1_to_sknp1] at hx₁x₂
        have: xr₁ ∈ CellAttached_boundary ∧ xr₂ ∈ CellAttached_boundary:= by
          rcases (eq_or_ne xr₁.1 xr₂.1) with heq' | hne'
          . have: xr₁.2 ≠ xr₂.2 := by
              contrapose! hne
              exact Sigma.subtype_ext heq' (congrArg Subtype.val hne)
            exact mem_boundary_of_same_char_image₁ (C:=C) xr₁.1.2 xr₂.1.2 this (congrArg Subtype.val heq') hx₁x₂
          exact mem_boundary_of_same_char_image₂ (C:=C) xr₁.1.2 xr₂.1.2 (Subtype.coe_ne_coe.mpr hne') hx₁x₂
        refine glue_setoid_of_same_image _ _ this.1 this.2 ?heq
        simpa [CellAttached_f, characteristic_cn] using hx₁x₂
  case is_quot =>
    apply quotient_of_saturate_closed_image_closed
    case f_cont => apply skn_sum_cnp1_to_sknp1_cont
    case f_surj => apply skn_sum_cnp1_to_sknp1_surj
    intro S hS SClosed
    rw [is_closed_iff_is_closed_in_ce_less_than_dim]
    intro e h_e_dim
    let g₂ : (Skeleton X (n + 1)) → X := (↑)
    have g₂_inj: Function.Injective g₂ := Subtype.val_injective
    show IsClosed (closure e.1 ∩ g₂ '' (skn_sum_cnp1_to_sknp1 n '' S))
    match Nat.le_succ_iff.mp h_e_dim with
    | Or.inl dim_e_le_n =>
      let g₁ : (Skeleton X n) → X := (↑)
      have : closure e.1 ∩ g₂ '' (skn_sum_cnp1_to_sknp1 n '' S) = closure e.1 ∩ g₁ '' (Sum.inl ⁻¹' S) := by
        ext x
        refine Iff.intro ?mp ?mpr
        case mp =>
          intro hx
          use hx.1
          have ce_sub_Xn : closure e.1 ⊆ (Skeleton X n) := by
            apply (Skeleton X n).cell_closure_incl _ e.2
            show e.1 ⊆ (Skeleton X n)
            rwa [sub_skeleton_iff e]
          use ⟨x, ce_sub_Xn hx.1⟩
          simp [g₁]
          have: ∃ y ∈ S, x = g₂ (skn_sum_cnp1_to_sknp1 n y) := by
            rcases hx.2 with ⟨w, hw, heq1⟩
            rcases hw with ⟨u, hu, heq2⟩
            rw [←heq2] at heq1
            use u, hu, heq1.symm
          rcases this with ⟨t, ht, htx⟩
          have : x = g₂ (skn_sum_cnp1_to_sknp1 n (Sum.inl ⟨x, ce_sub_Xn hx.1⟩)) := by simp [g₂, skn_sum_cnp1_to_sknp1]
          rw [this] at htx
          rw [Set.ext_iff] at hS
          rw [←hS]
          use t, ht, (Subtype.val_injective htx).symm
        case mpr =>
          intro hx
          use hx.1
          rcases hx.2 with ⟨w, inl_w_in_S, hwx⟩
          use skn_sum_cnp1_to_sknp1 n (Sum.inl w), ⟨Sum.inl w, inl_w_in_S, rfl⟩
          simpa [g₂, skn_sum_cnp1_to_sknp1]
      rw [this]
      have : IsClosed (Sum.inl ⁻¹' S) := IsClosed.preimage continuous_inl SClosed
      rw [is_closed_iff_is_closed_in_ce_less_than_dim] at this
      apply this
      exact dim_e_le_n
    | Or.inr dim_e_eq_np1 =>
      -- inclusion map from cb to sum of cb
      let η : cb (n + 1) → (Σ_:CellOfDim (C := C) (n + 1), cb (n + 1)) := fun x ↦ ⟨⟨e, dim_e_eq_np1⟩, x⟩
      have η_continuous: Continuous η := by
        apply continuous_iff_coinduced_le.mpr
        rw [instTopologicalSpaceSigma]
        exact le_iSup_iff.mpr fun b a ↦ a _
      let φ : cb (n + 1) → X := fun x ↦ C.characteristic_map e ((congrArg (fun p ↦ (cb p : Type)) dim_e_eq_np1).mpr x)
      have φ_closed_map: IsClosedMap φ := by
        apply @Eq.rec ℕ (C.dim_map e)
          (fun m hem ↦ IsClosedMap (fun x:cb m ↦ C.characteristic_map e (((congrArg (fun p ↦ (cb p : Type)) hem)).mpr x)))
          (by simp; apply Continuous.isClosedMap (C.characteristic_map_continuous e))
        exact dim_e_eq_np1
      -- we shall be able to prove φ is closed map
      -- but this lemma shall be proved
      have: closure e.1 ∩ g₂ '' (skn_sum_cnp1_to_sknp1 n '' S) = φ '' (η ⁻¹' (Sum.inr ⁻¹' S)) := by
        ext x
        refine Iff.intro ?mp ?mpr
        case mp =>
          rintro ⟨x_in_ce, ⟨_, ⟨w, w_in_S, rfl⟩, rfl⟩⟩
          rw [←characteristic_map_range, Set.mem_range] at x_in_ce
          rcases x_in_ce with ⟨y, hy⟩
          rw [←hy]
          let p := (congrArg (fun p ↦ (cb p : Type)) dim_e_eq_np1).mp y
          have hp: φ p = C.characteristic_map e y := by simp [φ, p]
          rw [←hp]
          rw [hy] at hp
          use p
          have hp': g₂ (skn_sum_cnp1_to_sknp1 n (Sum.inr (η p))) = φ p := by simp [φ, skn_sum_cnp1_to_sknp1, η, g₂]
          have hp_in_S: Sum.inr (η p) ∈ S := by
            rw [←hS]
            use w, w_in_S
            apply g₂_inj
            rw [←hp, hp']
          simpa
        case mpr =>
          intro hx
          rcases hx with ⟨w, hw, rfl⟩
          have : φ w ∈ closure e := by
            rw [←characteristic_map_range, Set.mem_range]
            use (congrArg (fun p ↦ (cb p : Type)) dim_e_eq_np1).mpr w
          use this
          have : Sum.inr (η w) ∈ S := hw
          use (skn_sum_cnp1_to_sknp1 n (Sum.inr (η w))), (by use (Sum.inr (η w)))
          simp [g₂, skn_sum_cnp1_to_sknp1, η, φ]
      rw [this]
      apply φ_closed_map
      exact IsClosed.preimage η_continuous (IsClosed.preimage continuous_inr SClosed)

end

section helper
variable {X: Type*} [TopologicalSpace X]
variable {Y: Type*} [TopologicalSpace Y]
theorem aux_subspace_topology_eq {S: Set X} [TS: TopologicalSpace S] (h: ∀ (b: Set S), @IsClosed S TS b ↔ @IsClosed X _ ((↑) '' b)): TS = instTopologicalSpaceSubtype := by
  suffices ∀ (b:Set S), @IsClosed _ TS b ↔ @IsClosed _ instTopologicalSpaceSubtype b by
    ext s
    simp only [←isClosed_compl_iff, this]
  have S_closed : IsClosed S := by
    rw [←Subtype.coe_image_univ S, ←h]
    exact isClosed_univ
  intro b
  rw [h]
  refine Iff.intro ?mp ?mpr
  case mp =>
    intro hb
    use ((↑) '' b)ᶜ, hb.isOpen_compl
    simp
  case mpr =>
    intro hb
    exact S_closed.isClosedMap_subtype_val b hb
theorem is_closed_map_id : IsClosedMap (id: X → X) := by
  intro U UClosed
  simp [UClosed]
theorem induced_of_cont {f: X → Y} (hf: ∀ s: Set X, IsClosed s → ∃ t: Set Y, IsClosed t ∧ s = f ⁻¹' t) (fcont: Continuous f): Topology.IsInducing f := by
  refine { eq_induced := ?_ }
  ext s
  refine Iff.intro ?mp ?mpr
  case mp =>
    intro hs
    have : IsClosed sᶜ := isClosed_compl_iff.mpr hs
    show ∃ t, IsOpen t ∧ f ⁻¹' t = s
    rcases (hf sᶜ) (isClosed_compl_iff.mpr hs) with ⟨t, t_closed, s_compl_eq⟩
    use tᶜ
    simp [t_closed, ←s_compl_eq]
  case mpr =>
    rintro ⟨t, t_open, rfl⟩
    exact fcont.isOpen_preimage t t_open
end helper

section
class CWComplexConstructor (X: Type*) where
  Fsk: ℕ → Set X
  Fsk0_nonempty: (Fsk 0).Nonempty
  Fsk_chain: ∀ n: ℕ, Fsk n ⊆ Fsk (n + 1)
  Fsk_cover: ⋃n:ℕ, Fsk n = Set.univ
  Tsk: (n:ℕ) → TopologicalSpace (Fsk n)  -- topology on skeletons
  Tsk0_discrete: DiscreteTopology (Fsk 0)
  Fι: ℕ → Type*   -- indexing type for gluing closed balls
  Ff: (n:ℕ) → {(x: Σ_:(Fι n), cb (n + 1)) | x.2 ∈ cb_boundary} → (Fsk n)  -- gluing function sending set of closed ball's boundary to skeleton n
  Ff_continuous: ∀ n, Continuous (Ff n)
  Fφ: (n:ℕ) → (AdjointSpace _ (Ff n)) → (Fsk (n + 1))
  Fφ_heomorph: ∀ n:ℕ, IsHomeomorph (Fφ n)
  Fφ_fix: ∀ n:ℕ, (Fφ n) ∘ (left_adj_proj _ (Ff n)) = fun x ↦ ⟨x.1,  (Fsk_chain n) x.2⟩

variable {X: Type*}
variable [CWC: CWComplexConstructor X]
instance {n:ℕ}: TopologicalSpace (CWC.Fsk n) := CWC.Tsk n

-- this topology is the same with what is defined by text
instance instCWConstructorTopology : TopologicalSpace X where
  IsOpen := fun s ↦ ∀ n:ℕ, IsOpen ((Subtype.val : (CWC.Fsk n) → X) ⁻¹' s)
  isOpen_univ := by simp
  isOpen_inter := by
    intro s t hs ht n
    rw [Set.preimage_inter]
    apply IsOpen.inter (hs n) (ht n)
  isOpen_sUnion := by
    intro ss hss n
    rw [Set.preimage_sUnion]
    apply isOpen_sUnion
    intro t ht
    simp at ht
    rcases ht with ⟨y, hy, rfl⟩
    apply isOpen_sUnion
    intro t ht
    simp at ht
    rcases ht with ⟨y', hy', rfl⟩
    apply hss y y'

theorem Fsk_incl {m n: ℕ} (hmn: m ≤ n) : CWC.Fsk m ⊆ CWC.Fsk n := by
  rcases Nat.exists_eq_add_of_le hmn with ⟨k, rfl⟩
  induction' k with k ik
  . simp
  trans (CWC.Fsk (m + k))
  . exact ik (Nat.le_add_right m k)
  rw [←add_assoc]
  apply CWC.Fsk_chain

lemma Fsk_chain_incl_continuous {n: ℕ}: Continuous ((fun x ↦ ⟨x.1, CWC.Fsk_chain _ x.2⟩): CWC.Fsk n → CWC.Fsk (n + 1)) := by
  rw [←CWC.Fφ_fix]
  refine Continuous.comp ?φ_cont ?left_adj_proj_cont
  case φ_cont => exact (CWC.Fφ_heomorph n).continuous
  case left_adj_proj_cont =>
    apply Topology.IsEmbedding.continuous
    refine left_adj_proj_is_embedding _ _ ?hAClosed (CWC.Ff_continuous n)
    rw [isClosed_sigma_iff]
    intro i
    simp [cb_boundary_closed]

theorem Fsk_incl_continuous {m n: ℕ} (hmn: m ≤ n): Continuous ((fun x ↦ ⟨x.1, Fsk_incl hmn x.2⟩): CWC.Fsk m → CWC.Fsk n) := by
  rcases Nat.exists_eq_add_of_le hmn with ⟨k, rfl⟩
  have aux: ∀ p q:ℕ, (h:p = q) → Continuous ((fun x ↦ ⟨x.1, Fsk_incl (Nat.le_of_eq h) x.2⟩):CWC.Fsk p → CWC.Fsk q) := by
    intro p q h
    exact @Eq.rec ℕ p (fun (p':ℕ) (eq:p=p') ↦ Continuous ((fun x ↦ ⟨x.1, Fsk_incl (Nat.le_of_eq eq) x.2⟩): CWC.Fsk p → CWC.Fsk p')) continuous_id q h
  induction' k with k ik
  . apply aux
    norm_num
  let f₁ : CWC.Fsk m → CWC.Fsk (m + k) := fun x ↦ ⟨x.1, Fsk_incl (Nat.le_add_right m k) x.2⟩
  let f₂ : CWC.Fsk (m + k) → CWC.Fsk (m + k + 1) := fun x ↦ ⟨x.1, CWC.Fsk_chain _ x.2⟩
  let f₃ : CWC.Fsk (m + k + 1) → CWC.Fsk (m + (k + 1)) := fun x ↦ ⟨x.1, Fsk_incl (Nat.le_of_eq (by rw[add_assoc])) x.2⟩
  let f : CWC.Fsk m → CWC.Fsk (m + (k + 1)) := fun x ↦ ⟨x.1, Fsk_incl hmn x.2⟩
  show Continuous f
  have: f = f₃ ∘ f₂ ∘ f₁ := by
    ext x
    simp [f, f₁, f₂, f₃]
  rw [this]
  have cont₁: Continuous f₁ := ik (Nat.le_add_right m k)
  have cont₂: Continuous f₂ := by apply Fsk_chain_incl_continuous
  have cont₃: Continuous f₃ := by
    apply aux
    rw [add_assoc]
  exact Continuous.comp cont₃ (Continuous.comp cont₂ cont₁)

lemma Fsk_chain_incl_closed_map {n:ℕ}: IsClosedMap ((fun x ↦ ⟨x.1, CWC.Fsk_chain _ x.2⟩): CWC.Fsk n → CWC.Fsk (n + 1)) := by
  rw [←CWC.Fφ_fix]
  refine IsClosedMap.comp ?φ_closed ?left_adj_proj_closed
  case φ_closed => exact (CWC.Fφ_heomorph n).isClosedMap
  case left_adj_proj_closed =>
    refine left_adj_proj_closed_map _ _ ?hAClosed (CWC.Ff_continuous n)
    rw [isClosed_sigma_iff]
    intro i
    simp [cb_boundary_closed]

theorem Fsk_incl_closed_map {m n: ℕ} (hmn: m ≤ n): IsClosedMap ((fun x ↦ ⟨x.1, Fsk_incl hmn x.2⟩): CWC.Fsk m → CWC.Fsk n) := by
  rcases Nat.exists_eq_add_of_le hmn with ⟨k, rfl⟩
  have aux: ∀ p q:ℕ, (h:p = q) → IsClosedMap ((fun x ↦ ⟨x.1, Fsk_incl (Nat.le_of_eq h) x.2⟩):CWC.Fsk p → CWC.Fsk q) := by
    intro p q h
    exact @Eq.rec ℕ p (fun (p':ℕ) (eq:p=p') ↦ IsClosedMap ((fun x ↦ ⟨x.1, Fsk_incl (Nat.le_of_eq eq) x.2⟩): CWC.Fsk p → CWC.Fsk p')) is_closed_map_id q h
  induction' k with k ik
  . apply aux
    simp
  let f₁ : CWC.Fsk m → CWC.Fsk (m + k) := fun x ↦ ⟨x.1, Fsk_incl (Nat.le_add_right m k) x.2⟩
  let f₂ : CWC.Fsk (m + k) → CWC.Fsk (m + k + 1) := fun x ↦ ⟨x.1, CWC.Fsk_chain _ x.2⟩
  let f₃ : CWC.Fsk (m + k + 1) → CWC.Fsk (m + (k + 1)) := fun x ↦ ⟨x.1, Fsk_incl (Nat.le_of_eq (by rw[add_assoc])) x.2⟩
  let f : CWC.Fsk m → CWC.Fsk (m + (k + 1)) := fun x ↦ ⟨x.1, Fsk_incl hmn x.2⟩
  show IsClosedMap f
  have: f = f₃ ∘ f₂ ∘ f₁ := by
    ext x
    simp [f, f₁, f₂, f₃]
  rw [this]
  have c₁: IsClosedMap f₁ := ik (Nat.le_add_right m k)
  have c₂: IsClosedMap f₂ := by apply Fsk_chain_incl_closed_map
  have c₃: IsClosedMap f₃ := by
    apply aux
    rw [add_assoc]
  exact IsClosedMap.comp c₃ (IsClosedMap.comp c₂ c₁)

lemma closed_in_cwc_iff {n: ℕ}: ∀ (b: Set (CWC.Fsk n)), IsClosed b ↔ IsClosed (((↑): CWC.Fsk n → X) '' b) := by
  intro b
  refine Iff.intro ?mp ?mpr
  case mp =>
    intro hb
    rw [←@isOpen_compl_iff]
    intro m
    show IsOpen ((((↑): CWC.Fsk m → X) ⁻¹' ((↑) '' b))ᶜ)
    rw [@isOpen_compl_iff]
    rcases Nat.le_total m n with m_le_n | n_le_m
    . let f : CWC.Fsk m → CWC.Fsk n := fun x ↦ ⟨x.1, Fsk_incl m_le_n x.2⟩
      have: ((↑): CWC.Fsk m → X) ⁻¹' (((↑): CWC.Fsk n → X) '' b) = f ⁻¹' b := by
        ext x
        simp [f]
        refine Iff.intro ?mp' ?mpr'
        case mp' =>
          rintro ⟨hx, x_in_b⟩
          exact x_in_b
        case mpr' =>
          intro x_in_b
          use Fsk_incl m_le_n x.2
      rw [this]
      exact IsClosed.preimage (Fsk_incl_continuous m_le_n) hb
    . let f : CWC.Fsk n → CWC.Fsk m := fun x ↦ ⟨x.1, Fsk_incl n_le_m x.2⟩
      have: ((↑): CWC.Fsk m → X) ⁻¹' (((↑): CWC.Fsk n → X) '' b) = f '' b := by
        ext x
        simp [f]
        refine Iff.intro ?mp' ?mpr'
        case mp' =>
          rintro ⟨x_in_skn, x_in_b⟩
          use x.1, x_in_skn
        case mpr' =>
          rintro ⟨x', ⟨x'_in_skn, x'_in_b, rfl⟩⟩
          use x'_in_skn
      rw [this]
      apply (Fsk_incl_closed_map n_le_m)
      exact hb
  case mpr =>
    intro b_closed_in_X
    rw [←@isOpen_compl_iff] at b_closed_in_X
    rw [←@isOpen_compl_iff]
    simpa using b_closed_in_X n

theorem Tsk_eq_subspace: ∀ n:ℕ, CWC.Tsk n = instTopologicalSpaceSubtype := by
  intro n
  apply aux_subspace_topology_eq
  apply closed_in_cwc_iff

theorem Fsk_closed: ∀ n:ℕ, IsClosed (CWC.Fsk n) := by
  intro n
  rw [←(Subtype.coe_image_univ (CWC.Fsk n)), ←closed_in_cwc_iff]
  exact isClosed_univ

theorem Fsk_coeherent: IsCoeherent (Set.range CWC.Fsk) := by
  refine { open_crit := ?_, cover := (by simpa using CWC.Fsk_cover)}
  simp
  intro s
  refine Iff.intro ?mp ?mpr
  case mp =>
    intro hs
    exact fun a ↦ IsOpen.preimage_val hs
  case mpr =>
    intro hs
    intro n
    have: @IsOpen _ (CWC.Tsk n) (((↑): CWC.Fsk n → X) ⁻¹' s) ↔ @IsOpen _ (instTopologicalSpaceSubtype) (((↑): CWC.Fsk n → X) ⁻¹' s) := by
      exact Eq.to_iff (congrFun (congrArg (@IsOpen (CWC.Fsk n)) (Tsk_eq_subspace n)) (((↑): CWC.Fsk n → X) ⁻¹' s))
    rw [this]
    exact hs n

lemma singleton_in_sk0_closed: ∀ x:X, x ∈ CWC.Fsk 0 → IsClosed {x} := by
  intro x x_in_sk0
  let x' : CWC.Fsk 0 := ⟨x, x_in_sk0⟩
  have singleton_eq: {x} = ((↑): CWC.Fsk 0 → X) '' {x'} := Eq.symm Set.image_singleton
  rw [singleton_eq]
  rw [←closed_in_cwc_iff]
  apply @isClosed_discrete (CWC.Fsk 0) (CWC.Tsk 0) (CWC.Tsk0_discrete)

namespace CWComplexConstructor
def cell_of_dim0: Set (Set X) := {{x} | x ∈ CWC.Fsk 0}
-- using haskell pipe operator to ease expression of function composition
def pre_characteristic_map: (n: ℕ) → (Σ_:(CWC.Fι n), cb (n + 1)) → X :=
  fun n x ↦ Subtype.val <| (CWC.Fφ n) <| (adj_proj _ (CWC.Ff n)) <| Sum.inr x

def cell_define_map: (n:ℕ) → (CWC.Fι n) → b (n + 1) → X := fun n i x ↦ pre_characteristic_map n ⟨i, ⟨x.1, b_in_cb x.2⟩⟩

def cell_sets : Set (Set X) := {e | e ∈ cell_of_dim0 ∪ ⋃ n:ℕ, Set.range (fun (i: CWC.Fι n) ↦ Set.range <| cell_define_map n i) ∧ e.Nonempty}

theorem cell_sets_nonempty: ∀ e ∈ cell_sets (CWC := CWC), e.Nonempty := by
  intro e e_in_sets
  exact e_in_sets.2

lemma Fsk_n_cell_np1_disjoint: ∀ n:ℕ, ∀ i:(CWC.Fι n), Disjoint (CWC.Fsk n) (Set.range (cell_define_map n i)) := by
  intro n i
  let f : (CWC.Fsk (n + 1)) → X := (↑)
  have Xn_eq : CWC.Fsk n = f '' ((CWC.Fφ n) '' (Set.range (left_adj_proj _ (CWC.Ff n)))) := by
    rw [←Set.image_univ]
    nth_rw 2 [←Set.image_comp]
    rw [CWC.Fφ_fix, ←Set.image_comp]
    have : f ∘ (fun (x:CWC.Fsk n) ↦ ⟨x.1, (CWC.Fsk_chain n) x.2⟩) = Subtype.val := by
      ext x
      simp [f]
    rw [this]
    exact Eq.symm (Subtype.coe_image_univ (CWComplexConstructor.Fsk n))
  have cell_eq: Set.range (cell_define_map n i) ⊆ f '' ((CWC.Fφ n) '' (Set.range (right_adj_proj _ (CWC.Ff n)))) := by
    intro x hx
    simp [cell_define_map] at hx
    rcases hx with ⟨u, hu, u_maps_to_x⟩
    rw [pre_characteristic_map] at u_maps_to_x
    let v: cb (n + 1) := ⟨u, b_in_cb hu⟩
    have iv_not_in_boundary : ⟨i, v⟩ ∈ {x:Σ_:(CWC.Fι n), cb (n + 1) | x.2 ∈ cb_boundary}ᶜ := by
      simp [←cb_boundary_inner_cmpl]
      use ⟨u, hu⟩
      simp [v]
    let z := (right_adj_proj _ (CWC.Ff n)) ⟨⟨i, v⟩, iv_not_in_boundary⟩
    use (CWC.Fφ n) z
    constructor
    . use z
      simp [z]
    simp [←u_maps_to_x, f]
    rfl
  suffices Disjoint (f '' (((CWC.Fφ n) '' (Set.range (left_adj_proj _ (CWC.Ff n)))))) (f '' (((CWC.Fφ n)'' (Set.range (right_adj_proj _ (CWC.Ff n)))))) by
    rw [Xn_eq]
    exact Disjoint.symm (Set.disjoint_of_subset cell_eq (fun ⦃a⦄ a ↦ a) (id (Disjoint.symm this)))
  rw [Set.disjoint_image_iff Subtype.val_injective, Set.disjoint_image_iff (CWC.Fφ_heomorph n).injective]
  apply left_adj_right_adj_range_disjoint

lemma Fsk_0_cell_disjoint : ∀ n:ℕ, ∀ i:(CWC.Fι n), Disjoint (CWC.Fsk 0) (Set.range (cell_define_map n i)) := by
  intro n
  induction' n with n ih
  . apply Fsk_n_cell_np1_disjoint
  intro i
  apply Set.disjoint_of_subset (Fsk_incl (Nat.le_add_left 0 (n + 1))) (fun ⦃a⦄ a ↦ a)
  apply Fsk_n_cell_np1_disjoint

lemma cell0_sub_Fsk0: ∀ e ∈ cell_of_dim0, e ⊆ CWC.Fsk 0 := by
  rintro _ ⟨x, x_in_cd0, rfl⟩
  exact Set.singleton_subset_iff.mpr x_in_cd0

lemma cell_n_in_Fsk_np1: ∀ n:ℕ, ∀ i:(CWC.Fι n), (Set.range (cell_define_map n i)) ⊆ CWC.Fsk (n + 1) := by
  intro n i
  intro x hx
  simp [cell_define_map] at hx
  rcases hx with ⟨u, hu, u_maps_to_x⟩
  rw [pre_characteristic_map] at u_maps_to_x
  have: CWC.Fsk (n + 1) = Set.range (((↑): CWC.Fsk (n + 1) → X) ∘ (CWC.Fφ n)) := by
    rw [Set.range_comp, Set.range_eq_univ.mpr (CWC.Fφ_heomorph n).surjective]
    exact Eq.symm (Subtype.coe_image_univ (CWComplexConstructor.Fsk (n + 1)))
  rw [this, ←u_maps_to_x]
  simp

lemma cell_of_different_n_disjoint: ∀ n₁:ℕ, ∀ i₁:(CWC.Fι n₁), ∀ n₂:ℕ, ∀ i₂:(CWC.Fι n₂), n₁ ≠ n₂ → Disjoint (Set.range (cell_define_map n₁ i₁)) (Set.range (cell_define_map n₂ i₂)) := by
  intro n₁ i₁ n₂ i₂ n₁n₂_ne
  wlog n₁_lt_n₂:n₁ < n₂ generalizing n₁ i₁ n₂ i₂
  . have n₂_lt_n₁: n₂ < n₁ := by
      rcases Nat.lt_or_lt_of_ne n₁n₂_ne with h₁ | h₂
      . contradiction
      exact h₂
    apply Disjoint.symm
    exact this n₂ i₂ n₁ i₁ n₁n₂_ne.symm n₂_lt_n₁
  rcases Nat.exists_eq_add_of_le n₁_lt_n₂ with ⟨k, rfl⟩
  induction' k with k ih
  . apply Set.disjoint_of_subset (cell_n_in_Fsk_np1 n₁ i₁) (fun ⦃a⦄ a ↦ a)
    exact Fsk_n_cell_np1_disjoint (n₁ + 1) i₂
  have: Set.range (cell_define_map n₁ i₁) ⊆ CWC.Fsk (n₁.succ + (k + 1)) := by
    trans CWC.Fsk (n₁ + 1)
    . apply cell_n_in_Fsk_np1
    apply Fsk_incl
    exact n₁_lt_n₂
  apply Set.disjoint_of_subset (this) (fun ⦃a⦄ a ↦ a)
  apply Fsk_n_cell_np1_disjoint

lemma cell_of_same_n_different_i_disjoint: ∀ n:ℕ, ∀ (i₁ i₂:(CWC.Fι n)), i₁ ≠ i₂ → Disjoint (Set.range (cell_define_map n i₁)) (Set.range (cell_define_map n i₂)) := by
  intro n i₁ i₂ i₁_ne_i₂
  let A: (Set (Σ_:(CWC.Fι n), cb (n + 1))) := {x | x.2 ∈ cb_boundary}
  let B: (Set (Σ_:(CWC.Fι n), cb (n + 1))) := {x | x.2 ∈ cb_inner}
  have B_eq_A_compl: B = Aᶜ := by
    ext x
    refine Iff.intro ?mp ?mpr
    case mp =>
      intro x_in_B
      show x.2 ∈ cb_boundaryᶜ
      simp [←cb_boundary_inner_cmpl]
      exact x_in_B
    case mpr =>
      intro x_in_A
      have : x.2 ∈ cb_boundaryᶜ := x_in_A
      simp [←cb_boundary_inner_cmpl] at this
      exact this
  let f: (Aᶜ: (Set (Σ_:(CWC.Fι n), cb (n + 1))))→ X := fun x ↦ Subtype.val <| (CWC.Fφ n) <| (right_adj_proj _ (CWC.Ff n)) x
  let S: (CWC.Fι n) → (Set (Aᶜ: (Set (Σ_:(CWC.Fι n), cb (n + 1))))) := fun i ↦ {x | x.1.1 = i}
  have cell_rw: ∀ i:(CWC.Fι n), (Set.range (cell_define_map n i)) = f '' (S i) := by
    intro i
    ext x
    refine Iff.intro ?mp ?mpr
    case mp =>
      intro x_in_range
      rcases x_in_range with ⟨w, rfl⟩
      rw [cell_define_map, pre_characteristic_map]
      let u : (Σ_:(CWC.Fι n), cb (n + 1)) := ⟨i, ⟨w.1, b_in_cb w.2⟩⟩
      have u_in_A_compl : u ∈ Aᶜ := by
        rw [←B_eq_A_compl]
        use w
        rfl
      use ⟨u, u_in_A_compl⟩, rfl
      simp [f, u, right_adj_proj]
    case mpr =>
      intro x_in_fSi
      rcases x_in_fSi with ⟨w, w_in_S, rfl⟩
      have w'_in_B: w.1 ∈ B := by
        rw [B_eq_A_compl]
        exact w.2
      rcases w'_in_B with ⟨u, hu⟩
      have heq: w.1 = ⟨i, ⟨u,  b_in_cb u.2⟩ ⟩ := by
        exact Sigma.subtype_ext w_in_S (congrArg Subtype.val (id (Eq.symm hu)))
      use u
      simp [cell_define_map, pre_characteristic_map, f, right_adj_proj, heq]
  have f_inj: Function.Injective f := by
    apply Function.Injective.comp
    . exact Subtype.val_injective
    apply Function.Injective.comp
    . exact (CWC.Fφ_heomorph n).injective
    apply right_adj_proj_injective
  rw [cell_rw i₁, cell_rw i₂]
  refine (Set.disjoint_image_iff f_inj).mpr ?_
  refine Set.disjoint_iff_forall_ne.mpr ?_
  intro a ha b hb
  suffices a.1.1 ≠ b.1.1 by
    exact fun a_1 ↦ this (congrArg Sigma.fst (congrArg Subtype.val a_1))
  rw [ha, hb]
  exact i₁_ne_i₂

theorem cell_sets_disjoint: (cell_sets (CWC := CWC)).Pairwise Disjoint := by
  intro e₁ e₁_in_sets e₂ e₂_in_sets e₁_ne_e₂
  rcases e₁_in_sets with ⟨e₁_in_X0|e₁_in_Xn, e₁_nonempty⟩
  . rcases e₂_in_sets with ⟨e₂_in_X0|e₂_in_Xn, e₂_nonempty⟩
    . -- e₁ and e₂ are singleton
      rcases e₁_in_X0 with ⟨x₁, x₁_in_Fsk0, rfl⟩
      rcases e₂_in_X0 with ⟨x₂, x₂_in_Fsk0, rfl⟩
      -- generated by apply?
      exact Set.disjoint_singleton.mpr fun a ↦ e₁_ne_e₂ (congrArg singleton a)
    . simp at e₂_in_Xn
      rcases e₂_in_Xn with ⟨n, i, rfl⟩
      apply Set.disjoint_of_subset (cell0_sub_Fsk0 _ e₁_in_X0) (fun ⦃a⦄ a ↦ a)
      apply Fsk_0_cell_disjoint
  . simp at e₁_in_Xn
    rcases e₁_in_Xn with ⟨n₁, i₁, rfl⟩
    rcases e₂_in_sets with ⟨e₂_in_X0|e₂_in_Xn, e₂_nonempty⟩
    . apply Disjoint.symm
      apply Set.disjoint_of_subset (cell0_sub_Fsk0 _ e₂_in_X0) (fun ⦃a⦄ a ↦ a)
      apply Fsk_0_cell_disjoint
    . simp at e₂_in_Xn
      rcases e₂_in_Xn with ⟨n₂, i₂, rfl⟩
      rcases eq_or_ne n₁ n₂ with n₁_eq_n₂ | n₁_ne_n₂
      . have e₂_eq: Set.range (cell_define_map n₂ i₂) = Set.range (cell_define_map n₁ ((congrArg CWC.Fι n₁_eq_n₂).mpr i₂)) := by
          apply Eq.rec (motive := (fun n₂ eq ↦ ∀ i:(CWC.Fι n₂), Set.range (cell_define_map n₂ i) = Set.range (cell_define_map n₁ ((congrArg CWC.Fι eq).mpr i)))) (fun i ↦ rfl) n₁_eq_n₂
        rw [e₂_eq]
        have: i₁ ≠ ((congrArg CWC.Fι n₁_eq_n₂).mpr i₂) := by
          contrapose! e₁_ne_e₂
          rw [e₂_eq, e₁_ne_e₂]
        apply cell_of_same_n_different_i_disjoint
        exact this
      . apply cell_of_different_n_disjoint
        exact n₁_ne_n₂

lemma Fsk_cover' : ∀ x:X, ∃ n:ℕ, x ∈ CWC.Fsk n := by
  rw [←Set.iUnion_eq_univ_iff]
  exact CWC.Fsk_cover

lemma mem_cell_in_adj_sk {x: X} {n: ℕ} (x_not_in_Fsk_n: x ∉ CWC.Fsk n) (x_in_Fsk_np1: x ∈ CWC.Fsk (n + 1)) : ∃ (i:CWC.Fι n), x ∈ Set.range (cell_define_map n i) := by
  let y : (CWC.Fsk (n + 1)) := ⟨x, x_in_Fsk_np1⟩
  have y_coe_to_x: x = Subtype.val y := rfl
  rcases (CWC.Fφ_heomorph n).surjective y with ⟨w, w_maps_to_y⟩
  have w_in_right_range: w ∈ Set.range (right_adj_proj _ (CWC.Ff n)) := by
    rw [right_range_eq_left_range_compl]
    show w ∉ (Set.range (left_adj_proj _ (CWC.Ff n)))
    contrapose! x_not_in_Fsk_n
    rw [Set.mem_range] at x_not_in_Fsk_n
    rcases x_not_in_Fsk_n with ⟨x', x'_mapsto_w⟩
    have: (CWC.Fφ n) ((left_adj_proj _ (CWC.Ff n)) x') = ((CWC.Fφ n) ∘ (left_adj_proj _ (CWC.Ff n))) x' := rfl
    rw [←x'_mapsto_w, this, CWC.Fφ_fix, ←SetCoe.ext_iff] at w_maps_to_y
    simp at w_maps_to_y
    show y.1 ∈ CWC.Fsk n
    rw [←w_maps_to_y]
    exact x'.2
  rcases w_in_right_range with ⟨z, rfl⟩
  have : z.1.2 ∈ cb_inner := by rw [cb_inner_eq_boundary_compl]; exact z.2
  rcases this with ⟨q, q_is_z⟩
  use z.1.1, q
  have z_coe: ⟨z.1.1, ⟨q.1, b_in_cb q.2⟩⟩ = Subtype.val z := by
    have: Subtype.val z = ⟨z.1.1, z.1.2⟩ := rfl
    nth_rw 2 [this]
    apply congrArg (Sigma.mk z.1.1)
    rw [←q_is_z]
    rfl
  rw [cell_define_map, pre_characteristic_map, y_coe_to_x, Subtype.val_inj, ←w_maps_to_y, (CWC.Fφ_heomorph n).injective.eq_iff, z_coe]
  rfl

theorem cell_sets_cover: ⋃₀ (cell_sets (CWC := CWC)) = Set.univ := by
  rw [Set.sUnion_eq_univ_iff]
  intro x
  let Sn := {n:ℕ | x ∈ CWC.Fsk n}
  have Sn_nonempty:  Sn.Nonempty := by
    rcases Fsk_cover' x with ⟨n₀, hn₀⟩
    use n₀, hn₀
  let n := WellFounded.min wellFounded_lt Sn Sn_nonempty
  have x_in_Fskn : x ∈ CWC.Fsk n := WellFounded.min_mem wellFounded_lt Sn Sn_nonempty
  rcases Nat.eq_zero_or_pos n with n_eq_0 | n_gt_0
  . rw [n_eq_0] at x_in_Fskn
    use {x}
    simp [cell_sets, cell_of_dim0, x_in_Fskn]
  . have:  0 < n := n_gt_0
    rw [←Nat.exists_eq_add_one] at this
    rcases this with ⟨k, n_eq_k_succ⟩
    have k_lt_n: k < n := by linarith
    have x_not_in_Fsk_k : x ∉ CWC.Fsk k := by
      contrapose! k_lt_n
      apply WellFounded.min_le
      exact k_lt_n
    rw [n_eq_k_succ] at x_in_Fskn
    rcases mem_cell_in_adj_sk (CWC := CWC) x_not_in_Fsk_k x_in_Fskn with ⟨i, x_in_ki⟩
    use Set.range (cell_define_map k i)
    rw [and_comm]; use x_in_ki
    constructor
    . right
      rw [Set.mem_iUnion]
      use k
      simp
    use x

lemma exists_skn_contain_cell: ∀ e ∈ cell_sets, ∃ n, e ⊆ CWC.Fsk n := by
  intro e e_in_sets
  rcases e_in_sets with ⟨e_in_sk0 | e_in_skn, e_nonempty⟩
  . use 0
    apply cell0_sub_Fsk0 _ e_in_sk0
  . simp at e_in_skn
    rcases e_in_skn with ⟨n, ⟨i, rfl⟩⟩
    use (n + 1)
    exact cell_n_in_Fsk_np1 n i

lemma cell_of_dim0_in_sets: ∀ e ∈ cell_of_dim0, e ∈ cell_sets (CWC:=CWC) := by
  rintro e ⟨x, x_in_sk0, rfl⟩
  constructor
  . left
    use x
  . exact Set.singleton_nonempty x

lemma cell_of_dim0_in_sets': ∀ x: X, x ∈ CWC.Fsk 0 → {x} ∈ cell_sets := by
  intro x x_in_sk0
  refine ⟨Or.inl ?_, Set.singleton_nonempty x⟩
  use x

lemma cell_define_map_range_in_sets: ∀ n, ∀ (i:CWC.Fι n), Set.range (cell_define_map n i) ∈ cell_sets := by
  intro n i
  constructor
  . right
    simp
    use n, i
  . exact Set.range_nonempty (cell_define_map n i)

noncomputable def dim_map : (cell_sets (CWC := CWC)) → ℕ := fun e ↦ WellFounded.min wellFounded_lt {n | e.1 ⊆ CWC.Fsk n} (by rcases exists_skn_contain_cell e.1 e.2 with ⟨n, hn ⟩; use n, hn)

lemma dim_map_cell_dim0_is_0 : ∀e, ∀ h:(e ∈ cell_of_dim0), dim_map ⟨e, cell_of_dim0_in_sets (CWC := CWC) e h⟩ = 0 := by
  rintro e ⟨x, x_in_sk0, e_is_x⟩
  suffices dim_map ⟨e, cell_of_dim0_in_sets e ⟨x, x_in_sk0, e_is_x⟩⟩ ≤ 0 by
    exact Nat.eq_zero_of_le_zero this
  apply WellFounded.min_le
  simp [←e_is_x, x_in_sk0]

lemma dim_map_cell_n_is_np1 : ∀ n:ℕ, ∀ (i: CWC.Fι n), dim_map ⟨Set.range (cell_define_map n i), cell_define_map_range_in_sets n i⟩ = (n + 1) := by
  intro n i
  let e : cell_sets := ⟨Set.range (cell_define_map n i), cell_define_map_range_in_sets n i⟩
  show dim_map e = n + 1
  have h_le: dim_map e ≤ n + 1 := by
    apply WellFounded.min_le
    apply cell_n_in_Fsk_np1
  have h_ge: dim_map e ≥ n + 1 := by
    by_contra! dim_map_e_lt_np1
    have dim_map_e_le_n: dim_map e ≤ n := Nat.le_of_lt_succ dim_map_e_lt_np1
    have e_in_skn: e.1 ⊆ CWC.Fsk n := by
      trans CWC.Fsk (dim_map e)
      . show dim_map e ∈ {n | e.1 ⊆ CWC.Fsk n}
        apply WellFounded.min_mem
      . exact Fsk_incl dim_map_e_le_n
    have e_eq_empty: e.1 = ∅ := Set.subset_empty_iff.mp ((Fsk_n_cell_np1_disjoint n i) e_in_skn (fun ⦃a⦄ a ↦ a))
    have e_ne_empty: e.1 ≠ ∅ := by
      rw [←Set.nonempty_iff_ne_empty]
      exact e.2.2
    contradiction
  linarith

lemma dim_map0_in_sk0: ∀ e:cell_sets, dim_map e = 0 → ∃ x:X, e.1 = {x} ∧ x ∈ CWC.Fsk 0 := by
  rintro ⟨e, e_in_sets⟩ dim_map_e_to_0
  rcases e_in_sets with ⟨e_in_cell0 | e_in_celln, e_non_empty⟩
  . rcases e_in_cell0 with ⟨x, x_in_sk0, rfl⟩
    use x
  . rw [Set.mem_iUnion] at e_in_celln
    rcases e_in_celln with ⟨n, ⟨i, e_eq⟩⟩
    simp at e_eq
    have e_sub_sk0: e ⊆ CWC.Fsk 0 := by
      show 0 ∈ {n | (⟨e, ⟨Or.inr e_in_celln, e_non_empty⟩⟩:cell_sets).1 ⊆ CWC.Fsk n}
      rw [←dim_map_e_to_0]
      apply WellFounded.min_mem
    have inter_empty: e ∩ CWC.Fsk 0 = ∅ := by
      rw [←Set.disjoint_iff_inter_eq_empty, ←e_eq, disjoint_comm]
      exact Fsk_0_cell_disjoint n i
    have inter_non_empty: e ∩ CWC.Fsk 0 ≠ ∅ := by
      rw [←Set.left_eq_inter] at e_sub_sk0
      rwa [←e_sub_sk0, ←Set.nonempty_iff_ne_empty]
    contradiction

def cell_sets₀ : Set (cell_sets (CWC:= CWC)) := {e | dim_map e = 0}

def cell_sets_indices := (CWC.Fsk 0) ⊕ (Σ(n:ℕ), CWC.Fι n)

def indices_to_Nat : (cell_sets_indices (CWC := CWC)) → ℕ := fun I ↦ match I with
| Sum.inl _ => 0
| Sum.inr ⟨n, _⟩ => n + 1

def indices_to_cb_to_X : (I: (cell_sets_indices (CWC := CWC))) → cb (indices_to_Nat (CWC := CWC) I) → X := fun I ↦ match I with
| Sum.inl ⟨x, _⟩ => fun _ ↦ x
| Sum.inr ⟨n, i⟩ => (Subtype.val) ∘ (CWC.Fφ n) ∘ (adj_proj _ (CWC.Ff n)) ∘ (@Sum.inr (CWC.Fsk n) _) ∘ (@Sigma.mk _ (fun _ ↦ cb (n + 1)) i)

def indices_to_cell: (cell_sets_indices (CWC := CWC)) → (cell_sets (CWC := CWC)) := fun I ↦ match I with
| Sum.inl ⟨x, x_in_sk0⟩ => ⟨{x}, ⟨by left; simp[cell_of_dim0, x_in_sk0] , Set.singleton_nonempty x ⟩⟩
| Sum.inr ⟨n, i⟩ => ⟨Set.range (cell_define_map n i), cell_define_map_range_in_sets n i⟩

lemma indices_to_cell_lr_ne (n: ℕ) (i: CWC.Fι n) (x: X) (hx: x ∈ CWC.Fsk 0) : indices_to_cell (Sum.inl ⟨x, hx⟩) ≠ indices_to_cell (Sum.inr ⟨n, i⟩) := by
  by_contra heq
  simp [indices_to_cell] at heq
  have : {x} ⊆ CWC.Fsk 0 := Set.singleton_subset_iff.mpr hx
  rw [heq] at this
  have: Set.range (cell_define_map n i) ≤ ⊥ := Fsk_0_cell_disjoint n i this (fun ⦃a⦄ a ↦ a)
  have eq_empty: Set.range (cell_define_map n i) = ∅ := Set.subset_eq_empty this rfl
  have ne_empty: Set.range (cell_define_map n i) ≠ ∅ := by
        rw [←Set.nonempty_iff_ne_empty]
        exact Set.range_nonempty (cell_define_map n i)
  contradiction

theorem indices_to_cell_injective: Function.Injective (indices_to_cell (CWC := CWC)):= by
  intro I1 I2 I1_I2_img_eq
  match I1 with
  | Sum.inl ⟨x₁, x₁_in_sk0⟩ =>
    match I2 with
    | Sum.inl ⟨x₂, x₂_in_sk0⟩ =>
      simp [indices_to_cell] at I1_I2_img_eq
      apply congrArg
      exact SetCoe.ext I1_I2_img_eq
    | Sum.inr ⟨n₂, i₂⟩ =>
      apply False.elim ((indices_to_cell_lr_ne n₂ i₂ x₁ x₁_in_sk0) I1_I2_img_eq)
  | Sum.inr ⟨n₁, i₁⟩ =>
    match I2 with
    | Sum.inl ⟨x₂, x₂_in_sk0⟩ =>
      apply False.elim ((indices_to_cell_lr_ne n₁ i₁ x₂ x₂_in_sk0) I1_I2_img_eq.symm)
    | Sum.inr ⟨n₂, i₂⟩ =>
      simp [indices_to_cell] at I1_I2_img_eq
      have n₁_n₂_eq: n₁ = n₂ := by
        by_contra! n₁_ne_n₂
        have hd: Disjoint (Set.range (cell_define_map n₁ i₁)) (Set.range (cell_define_map n₂ i₂)) := cell_of_different_n_disjoint n₁ i₁ n₂ i₂ n₁_ne_n₂
        rw [I1_I2_img_eq, Set.disjoint_iff_inter_eq_empty, Set.inter_self] at hd
        have h_nonempty: (Set.range (cell_define_map n₂ i₂)) ≠ ∅  := by
          rw [←Set.nonempty_iff_ne_empty]
          exact Set.range_nonempty (cell_define_map n₂ i₂)
        contradiction
      have: (⟨n₁, i₁⟩: Σn:ℕ, CWC.Fι n) = ⟨n₂, (congrArg CWC.Fι n₁_n₂_eq).mp i₁⟩ := by
        refine Sigma.mk.inj_iff.mpr ⟨n₁_n₂_eq, ?_⟩
        exact heq_of_eqRec_eq (congrArg (CWComplexConstructor.Fι X) n₁_n₂_eq) rfl
      rw [this]
      have range_rw: Set.range (cell_define_map n₁ i₁) = Set.range (cell_define_map n₂ ((congrArg CWC.Fι n₁_n₂_eq).mp i₁)) := by
        exact @Eq.rec ℕ n₁ (fun m n₁_eq_m ↦ Set.range (cell_define_map n₁ i₁) = Set.range (cell_define_map m ((congrArg CWC.Fι n₁_eq_m).mp i₁))) rfl n₂ n₁_n₂_eq
      rw [range_rw] at I1_I2_img_eq
      suffices (congrArg CWC.Fι n₁_n₂_eq).mp i₁ = i₂ by congr
      let i₁' := (congrArg CWC.Fι n₁_n₂_eq).mp i₁
      show i₁' = i₂
      by_contra! i₁'_ne_i₂
      have hd : Disjoint (Set.range (cell_define_map n₂ i₁')) (Set.range (cell_define_map n₂ i₂)) := cell_of_same_n_different_i_disjoint n₂ i₁' i₂ i₁'_ne_i₂
      rw [I1_I2_img_eq, Set.disjoint_iff_inter_eq_empty, Set.inter_self] at hd
      have h_nonempty: Set.range (cell_define_map n₂ i₂) ≠ ∅ := by
        rw [←Set.nonempty_iff_ne_empty]
        exact Set.range_nonempty (cell_define_map n₂ i₂)
      contradiction

theorem indices_to_cell_surjective : Function.Surjective (indices_to_cell (CWC := CWC)) := by
  rintro ⟨e, e_in_sets⟩
  rcases e_in_sets with ⟨e_in_sk0|e_in_skn, e_nonempty⟩
  . rcases e_in_sk0 with ⟨x, x_in_sk0, rfl⟩
    use Sum.inl ⟨x, x_in_sk0⟩
    rfl
  . rw [Set.mem_iUnion] at e_in_skn
    rcases e_in_skn with ⟨n, ⟨i, range_eq⟩⟩
    simp at range_eq
    use Sum.inr ⟨n, i⟩
    simp [indices_to_cell, range_eq]

instance cell_sets_indices_nonempty: Nonempty (cell_sets_indices (CWC := CWC)) := by
  rcases CWC.Fsk0_nonempty with ⟨x, x_in_sk0⟩
  use Sum.inl ⟨x, x_in_sk0 ⟩

noncomputable def cell_to_indices: (cell_sets (CWC := CWC)) → (cell_sets_indices (CWC := CWC)) := Function.invFun indices_to_cell

lemma cell_to_indices_left_inv: cell_to_indices ∘ (indices_to_cell (CWC := CWC))= id := by
  rw [cell_to_indices]
  refine Function.invFun_comp ?_
  exact indices_to_cell_injective

lemma cell_to_indices_left_inv': ∀ I, cell_to_indices (indices_to_cell (CWC := CWC) I) = I := by
  intro I
  show (cell_to_indices ∘ indices_to_cell) I = I
  rw [cell_to_indices_left_inv]
  rfl

lemma cell_to_indices_right_inv: (indices_to_cell (CWC := CWC)) ∘ cell_to_indices = id := by
  funext x
  simp [cell_to_indices]
  apply Function.invFun_eq
  revert x
  exact indices_to_cell_surjective

lemma cell_to_indices_on_dim0_cell {x: X} (x_in_sk0: x ∈ CWC.Fsk 0): cell_to_indices ⟨{x}, cell_of_dim0_in_sets' x x_in_sk0⟩ = Sum.inl ⟨x, x_in_sk0⟩ := by
  have: ⟨{x}, cell_of_dim0_in_sets' x x_in_sk0⟩ = indices_to_cell (Sum.inl ⟨x, x_in_sk0⟩) := by rw [indices_to_cell]
  rw [this, cell_to_indices_left_inv']

lemma cell_to_indices_on_dimn_cell {n: ℕ} (i: CWC.Fι n): cell_to_indices ⟨Set.range (cell_define_map n i), cell_define_map_range_in_sets n i⟩ = Sum.inr ⟨n, i⟩ := by
  have: ⟨Set.range (cell_define_map n i), cell_define_map_range_in_sets n i⟩ = indices_to_cell (Sum.inr ⟨n, i⟩) := by rw [indices_to_cell]
  rw [this, cell_to_indices_left_inv']

theorem dim_map_indices_to_nat_comm : ∀ e: (cell_sets (CWC := CWC)), indices_to_Nat (cell_to_indices e) = dim_map e := by
  rintro ⟨e, e_in_sets⟩
  rcases e_in_sets with ⟨e_in_sk0|e_in_skn, e_nonempty⟩
  . rw [dim_map_cell_dim0_is_0 e e_in_sk0]
    rcases e_in_sk0 with ⟨x, x_in_sk0, e_eq⟩
    have: ⟨e, ⟨Or.inl (Exists.intro x ⟨x_in_sk0, e_eq⟩), e_nonempty⟩⟩ = indices_to_cell (Sum.inl ⟨x, x_in_sk0⟩) := by simp [indices_to_cell, ←e_eq]
    simp [this, cell_to_indices_left_inv', indices_to_Nat]
  . rw [Set.mem_iUnion] at e_in_skn
    rcases e_in_skn with ⟨n, i, rfl⟩
    simp
    rw [dim_map_cell_n_is_np1]
    have : ⟨Set.range (cell_define_map n i), ⟨Or.inr e_in_skn, e_nonempty ⟩⟩ = indices_to_cell (Sum.inr ⟨n, i⟩) := by simp [indices_to_cell]
    simp [this, cell_to_indices_left_inv', indices_to_Nat]

noncomputable def characteristic_map : (e : (cell_sets (CWC := CWC))) → cb (dim_map e) → X := fun e ↦ (indices_to_cb_to_X (cell_to_indices e)) ∘ (congrArg (fun n ↦ (cb n:Type)) (dim_map_indices_to_nat_comm e).symm).mp

theorem characteristic_map_continuous : ∀ e: (cell_sets (CWC := CWC)),  Continuous (characteristic_map e) := by
  intro e
  rw [characteristic_map]
  refine Continuous.comp ?cont1 ?cont2
  case cont2 => exact @Eq.rec ℕ (dim_map e) (fun n heq ↦ Continuous (congrArg (fun m ↦ (cb m: Type)) heq).mp) continuous_id _ (dim_map_indices_to_nat_comm e).symm
  case cont1 =>
    rcases e with ⟨e, ⟨e_in_sk0|e_in_skn, e_nonempty⟩⟩
    . rcases e_in_sk0 with ⟨x, x_in_sk0, rfl⟩
      rw [cell_to_indices_on_dim0_cell x_in_sk0, indices_to_cb_to_X]
      exact continuous_const
    . rw [Set.mem_iUnion] at e_in_skn
      rcases e_in_skn with ⟨n, ⟨i, heq⟩⟩
      have eq1: e = Set.range (cell_define_map n i) := by exact heq.symm
      have eq2: (⟨e, ⟨Or.inr e_in_skn, e_nonempty⟩⟩: cell_sets) = ⟨Set.range (cell_define_map n i), cell_define_map_range_in_sets n i⟩ := by simp [eq1]
      rw [eq2, cell_to_indices_on_dimn_cell, indices_to_cb_to_X]
      have cont0: Continuous (@Sigma.mk (CWC.Fι n) (fun x ↦ ↑(cb (n + 1))) i) := continuous_sigmaMk
      have cont1: Continuous (@Sum.inr (↑(CWC.Fsk n)) ((_ : Fι X n) × ↑(cb (n + 1)))) := continuous_inr
      have cont2: Continuous (adj_proj _ (CWC.Ff n)) := by exact { isOpen_preimage := fun s a ↦ a }
      have cont3: Continuous (CWC.Fφ n) := (CWC.Fφ_heomorph n).continuous
      have cont4: Continuous (Subtype.val : CWC.Fsk (n + 1) → X) := { isOpen_preimage := fun s a ↦ a (n + 1)}
      exact (((cont4.comp cont3).comp cont2).comp cont1).comp cont0

theorem characteristic_map_inner_range: ∀ e:(cell_sets (CWC := CWC)), Set.range (cb_inner_map (characteristic_map e)) = e := by
  intro e
  rw [inner_map_range, characteristic_map, Set.image_comp]
  have : (congrArg (fun n ↦ (cb n:Type)) (dim_map_indices_to_nat_comm e).symm).mp '' cb_inner = cb_inner := by
    exact @Eq.rec ℕ (dim_map e) (fun m h ↦ (congrArg (fun p ↦ (cb p : Type)) h).mp '' cb_inner = cb_inner) (Set.image_id cb_inner) (indices_to_Nat (cell_to_indices e)) (dim_map_indices_to_nat_comm e).symm
  rw [this]
  rcases e with ⟨e, ⟨e_in_sk0|e_in_skn, e_nonempty⟩⟩
  . rcases e_in_sk0 with ⟨x, x_in_sk0, rfl⟩
    rw [cell_to_indices_on_dim0_cell x_in_sk0, indices_to_cb_to_X]
    simp
    ext t
    refine Iff.intro ?mp ?mpr
    case mp=>
      rintro ⟨p, p_in_cb_inner, hp⟩
      simp at hp
      exact id (Eq.symm hp)
    case mpr =>
      intro ht
      simp at ht
      use ⟨0, zero_in_cb⟩, zero_in_cb_inner
      simp [ht]
  . rw [Set.mem_iUnion] at e_in_skn
    rcases e_in_skn with ⟨n, ⟨i, heq⟩⟩
    simp at heq
    have eq1: cell_to_indices ⟨e, ⟨Or.inr e_in_skn, e_nonempty⟩⟩ = cell_to_indices ⟨Set.range (cell_define_map n i), cell_define_map_range_in_sets n i⟩ := by
      congr
      exact heq.symm
    rw [eq1, cell_to_indices_on_dimn_cell]
    show indices_to_cb_to_X (Sum.inr ⟨n, i⟩) '' (@cb_inner (n + 1)) = e
    rw [←heq]
    ext x
    refine Iff.intro ?mp ?mpr
    case mp =>
      rintro ⟨t, ⟨u, rfl⟩, t_eq⟩
      use u
      rw [←t_eq]
      rfl
    case mpr =>
      rintro ⟨u, hu⟩
      use b_to_cb u, (by use u)
      rw [←hu]
      rfl

lemma cb_cast_mp_inj {m n: ℕ} (heq: m = n): Function.Injective (congrArg (fun p ↦ (cb p: Type)) heq).mp := by
  apply @Eq.rec ℕ m (fun t eq ↦ Function.Injective (congrArg (fun p ↦ (cb p: Type)) eq).mp) (fun ⦃a₁ a₂⦄ a ↦ a)
  exact heq

lemma cb_cast_mp_inner_to_inner {m n: ℕ} (heq: m = n) {x: cb m} (hx: x ∈ cb_inner) : (congrArg (fun p ↦ (cb p: Type)) heq).mp x ∈ cb_inner := by
  apply @Eq.rec ℕ m (fun t eq ↦ (congrArg (fun p ↦ (cb p: Type)) eq).mp x ∈ cb_inner) hx
  exact heq
lemma cb_cast_mp_boundary_eq_boundary {m n: ℕ} (heq: m = n): (congrArg (fun p ↦ (cb p : Type)) heq).mp '' cb_boundary = cb_boundary := by
  apply @Eq.rec _ m (fun t eq ↦ (congrArg (fun p ↦ (cb p : Type)) eq).mp '' cb_boundary = cb_boundary) (Set.image_id _)
  exact heq
lemma indices_to_cb_to_X_inj_on_dim0_cells {x: X} (x_in_sk0: x ∈ CWC.Fsk 0) (u₁ u₂: cb (indices_to_Nat (cell_to_indices ⟨{x}, cell_of_dim0_in_sets' x x_in_sk0⟩ ))): u₁ = u₂ := by
  have dim_is_0: indices_to_Nat (cell_to_indices ⟨{x}, cell_of_dim0_in_sets' x x_in_sk0⟩) = 0 := by rw [cell_to_indices_on_dim0_cell x_in_sk0, indices_to_Nat]
  let f := (congrArg (fun n ↦ (cb n : Type)) dim_is_0).mp
  have f_inj: Function.Injective f := cb_cast_mp_inj dim_is_0
  have: f u₁ = f u₂ := by apply Subsingleton.allEq
  exact f_inj this

lemma indices_to_cb_to_X_inj_on_dimn_cells {n: ℕ} {i: CWC.Fι n} {u₁ u₂: cb (n + 1)} (hu₁: u₁ ∈ cb_inner) (hu₂: u₂ ∈ cb_inner) (heq: indices_to_cb_to_X (Sum.inr ⟨n, i⟩) u₁ = indices_to_cb_to_X (Sum.inr ⟨n, i ⟩) u₂) : u₁ = u₂ := by
  simp [indices_to_cb_to_X] at heq
  let A: (Set (Σ_:CWC.Fι n, cb (n + 1))) := {x | x.2 ∈ cb_boundary}
  have aux_mem: ∀ u : cb (n + 1), u ∈ cb_inner → ⟨i, u⟩ ∈ Aᶜ := by intro u u_mem ;simp [A]; rw [cb_boundary_eq_inner_compl]; simpa
  have aux_proj_eq: ∀ u: cb (n + 1), (h:(u ∈ cb_inner)) → adj_proj _ (CWC.Ff n) (Sum.inr ⟨i, u⟩) = right_adj_proj _ _ ⟨⟨i, u⟩, aux_mem u h⟩ := by intro u hu;simp [right_adj_proj]
  rw [aux_proj_eq u₁ hu₁, aux_proj_eq u₂ hu₂, Subtype.val_inj, (CWC.Fφ_heomorph n).injective.eq_iff, (right_adj_proj_injective _ _).eq_iff] at heq
  simpa using heq

lemma characteristic_map_inj_on_inner: ∀ e:(cell_sets (CWC := CWC)), Function.Injective (cb_inner_map (characteristic_map e)) := by
  intro e
  intro u₁ u₂ h_img_eq
  simp only [cb_inner_map, characteristic_map] at h_img_eq
  let f := (congrArg (fun n ↦ (cb n: Type)) (dim_map_indices_to_nat_comm e).symm).mp
  have f_inj: Function.Injective f := cb_cast_mp_inj (dim_map_indices_to_nat_comm e).symm
  let u₁' := f ⟨u₁, b_in_cb u₁.2⟩
  let u₂' := f ⟨u₂, b_in_cb u₂.2⟩
  have mem_inner₁ : u₁' ∈ cb_inner := by apply cb_cast_mp_inner_to_inner (Eq.symm (dim_map_indices_to_nat_comm e));use u₁;rfl
  have mem_inner₂ : u₂' ∈ cb_inner := by apply cb_cast_mp_inner_to_inner (Eq.symm (dim_map_indices_to_nat_comm e));use u₂;rfl
  have heq': (indices_to_cb_to_X (cell_to_indices e)) u₁' = (indices_to_cb_to_X (cell_to_indices e)) u₂' := h_img_eq
  suffices u₁' = u₂' by
    apply SetCoe.ext
    simpa using f_inj this
  rcases e with ⟨e, ⟨e_in_sk0|e_in_skn, e_nonempty⟩⟩
  . rcases e_in_sk0 with ⟨x, x_in_sk0, rfl⟩
    apply indices_to_cb_to_X_inj_on_dim0_cells x_in_sk0
  . rw [Set.mem_iUnion] at e_in_skn
    rcases e_in_skn with ⟨n, ⟨i, e_eq⟩⟩
    simp at e_eq
    have indice_eq: cell_to_indices ⟨e, ⟨Or.inr e_in_skn, e_nonempty⟩⟩ = Sum.inr ⟨n, i⟩ := by
      have: (⟨e, ⟨Or.inr e_in_skn, e_nonempty⟩⟩: cell_sets) = ⟨Set.range (cell_define_map n i), cell_define_map_range_in_sets n i⟩ := by apply SetCoe.ext;simp [e_eq]
      rw [this, cell_to_indices_on_dimn_cell]
    have dim_eq: indices_to_Nat (cell_to_indices ⟨e, ⟨Or.inr e_in_skn, e_nonempty⟩⟩) = n + 1 := by rw [indice_eq, indices_to_Nat]
    let g := (congrArg (fun p ↦ (cb p: Type)) dim_eq).mp
    have eq₁: indices_to_cb_to_X (cell_to_indices ⟨e, ⟨Or.inr e_in_skn, e_nonempty⟩⟩) = indices_to_cb_to_X (Sum.inr ⟨n, i⟩) ∘ g := by
      apply @Eq.rec _ (cell_to_indices ⟨e, ⟨Or.inr e_in_skn, e_nonempty⟩⟩) (fun e' eq ↦ indices_to_cb_to_X (cell_to_indices ⟨e, ⟨Or.inr e_in_skn, e_nonempty⟩⟩) = (indices_to_cb_to_X e') ∘ (congrArg (fun p ↦ (cb (indices_to_Nat p): Type)) eq).mp) rfl
      exact indice_eq
    simp [eq₁] at heq'
    suffices g u₁' = g u₂' by
      exact cb_cast_mp_inj dim_eq this
    have mem_inner₁' : g u₁' ∈ cb_inner := cb_cast_mp_inner_to_inner dim_eq mem_inner₁
    have mem_inner₂' : g u₂' ∈ cb_inner := cb_cast_mp_inner_to_inner dim_eq mem_inner₂
    apply indices_to_cb_to_X_inj_on_dimn_cells mem_inner₁' mem_inner₂' heq'

def b_to_sigma_b (n: ℕ) (i: CWC.Fι n): (b (n + 1)) → (↑{(x:Σ_:(CWC.Fι n), cb (n + 1)) | x.2 ∈ cb_boundary}ᶜ) := fun u ↦ ⟨⟨i, b_to_cb u⟩, (by simp[cb_boundary_eq_inner_compl]; use u; rfl)⟩

lemma b_to_sigma_b_inj {n:ℕ} {i: CWC.Fι n}: Function.Injective (b_to_sigma_b n i) := by
  intro t1 t2 heq
  simp [b_to_sigma_b] at heq
  exact SetCoe.ext heq

lemma sigma_boundary_closed (n: ℕ): IsClosed ({(x:Σ_:(CWC.Fι n), cb (n + 1)) | x.2 ∈ cb_boundary}) := by
  rw [isClosed_sigma_iff]
  intro i
  have: Sigma.mk i ⁻¹' ({(x:Σ_:(CWC.Fι n), cb (n + 1)) | x.2 ∈ cb_boundary}) = cb_boundary := by
    ext x
    simp
  rw [this]
  exact cb_boundary_closed

lemma b_to_sigma_b_is_induced {n: ℕ} {i: CWC.Fι n}: Topology.IsInducing (b_to_sigma_b n i) := by
  refine { eq_induced := ?_ }
  ext s
  refine Iff.intro ?mp ?mpr
  case mp =>
    intro hs
    use (b_to_sigma_b n i) '' s
    constructor
    . use (Subtype.val '' ((b_to_sigma_b n i) '' s))
      refine ⟨?_,  by apply (Subtype.val_injective).preimage_image⟩
      rw [isOpen_sigma_iff]
      intro i'
      rcases eq_or_ne i i' with i_eq_i' | i_ne_i'
      . rw [←i_eq_i']
        have: Sigma.mk i ⁻¹' (Subtype.val '' (b_to_sigma_b n i '' s)) = b_to_cb '' s := by
          ext x
          refine Iff.intro ?mp' ?mpr'
          case mp' =>
            rintro ⟨_, ⟨w, w_in_s, rfl⟩, heq⟩
            simp [b_to_sigma_b] at heq
            use w, w_in_s
            rw [←heq]; rfl
          case mpr' =>
            rintro ⟨y, y_in_s, rfl⟩
            use b_to_sigma_b n i y
            constructor
            . use y
            . rfl
        rw [this]
        exact b_to_cb_open_map s hs
      . have: Sigma.mk i' ⁻¹' (Subtype.val '' (b_to_sigma_b n i '' s)) = ∅ := by
          ext x
          refine Iff.intro ?mp' ?mpr'
          case mp' =>
            rintro ⟨y, ⟨z, z_in_s, rfl⟩, hy⟩
            simp [b_to_sigma_b] at hy
            rcases hy with ⟨i_eq_i', _⟩
            contradiction
          case mpr' =>
            intro hx
            contradiction
        simp [this]
    . apply (b_to_sigma_b_inj).preimage_image
  case mpr =>
    rintro ⟨t, ⟨u, u_open, rfl⟩, ht⟩
    have: s = b_to_cb ⁻¹' (((@Sigma.mk (CWC.Fι n) (fun p ↦ (cb (n + 1): Type)) i)) ⁻¹' u) := by
      ext x
      refine Iff.intro ?mp' ?mpr'
      case mp' =>
        intro hx
        rw [←ht] at hx
        exact hx
      case mpr' =>
        intro hx
        rw [←ht]
        exact hx
    rw [this]
    refine Continuous.isOpen_preimage ?_ (Sigma.mk i ⁻¹' u) ?_
    . exact b_to_cb_cont
    . refine IsOpen.preimage ?_ u_open
      exact continuous_sigmaMk

theorem characteristic_map_inducing_on_inner: ∀ e:(cell_sets (CWC := CWC)), Topology.IsInducing (cb_inner_map (characteristic_map e)) := by
  intro e
  rcases e with ⟨e, ⟨e_in_sk0|e_in_skn, e_nonempty⟩⟩
  . rcases e_in_sk0 with ⟨x, x_in_sk0, rfl⟩
    rw [characteristic_map]
    let x': cell_sets := ⟨{x}, ⟨Or.inl (Exists.intro x ⟨x_in_sk0, Eq.refl {x}⟩), e_nonempty⟩⟩
    rw [inner_map_eq_comp]
    have: Subsingleton (cb (indices_to_Nat (cell_to_indices x'))) := by
      rw [cell_to_indices_on_dim0_cell x_in_sk0, indices_to_Nat]
      infer_instance
    have induce₁: Topology.IsInducing (indices_to_cb_to_X (cell_to_indices x')) := by
      apply Topology.IsInducing.of_subsingleton
    have induce₂: Topology.IsInducing (congrArg (fun n ↦ (cb n : Type)) (dim_map_indices_to_nat_comm x').symm).mp := by
      apply @Eq.rec _ (dim_map x') (fun n eq ↦ Topology.IsInducing (congrArg (fun m ↦ (cb m: Type)) eq).mp) (Topology.IsInducing.id)
      exact (dim_map_indices_to_nat_comm x').symm
    apply (induce₁.comp induce₂).comp
    exact b_to_cb_inducing
  . rw [Set.mem_iUnion] at e_in_skn
    rcases e_in_skn with ⟨n, i, e_rw⟩
    simp at e_rw
    let e' : cell_sets := ⟨e, ⟨Or.inr e_in_skn, e_nonempty⟩⟩
    have dim_eq_np1 : dim_map e' = n + 1 := by
      have: e' = ⟨Set.range (cell_define_map n i), cell_define_map_range_in_sets n i⟩ := by
        apply SetCoe.ext;simp [e_rw]; rfl
      rw [this, dim_map_cell_n_is_np1]
    have ind_eq_np1: indices_to_Nat (cell_to_indices e') = n + 1 := by
      trans dim_map e'
      . exact dim_map_indices_to_nat_comm e'
      exact dim_eq_np1
    have ind_eq : cell_to_indices e' = Sum.inr ⟨n, i⟩ := by
      simp [e', ←e_rw]
      exact cell_to_indices_on_dimn_cell i
    let g := (congrArg (fun m ↦ (b m: Type)) dim_eq_np1).mp
    let f := b_to_sigma_b n i
    let h := (Subtype.val) ∘ (CWC.Fφ n) ∘ (right_adj_proj _ (CWC.Ff n)) ∘ f
    have g_inducing: Topology.IsInducing g := by
      apply @Eq.rec _ (dim_map e') (fun m eq ↦ Topology.IsInducing (congrArg (fun p ↦ (b p: Type)) eq).mp) Topology.IsInducing.id
      exact dim_eq_np1
    have f_inducing: Topology.IsInducing f := b_to_sigma_b_is_induced
    have h_inducing: Topology.IsInducing h := by
      apply Topology.IsInducing.comp
      . -- note  here the topology is Tsk, not the usual subspace topology, but we have proven such equality!
        apply @Eq.rec (TopologicalSpace (CWC.Fsk (n + 1))) instTopologicalSpaceSubtype (fun T Teq ↦ @Topology.IsInducing (CWC.Fsk (n + 1)) X T instCWConstructorTopology Subtype.val) Topology.IsInducing.subtypeVal
        exact Eq.symm (Tsk_eq_subspace (n + 1))
      . apply (CWC.Fφ_heomorph n).isInducing.comp
        apply (right_adj_proj_is_embedding _ (CWC.Ff n) (sigma_boundary_closed n)).isInducing.comp
        exact f_inducing
    have aux_decomp: cb_inner_map (characteristic_map e') = h ∘ g := by
      rw [inner_map_eq_comp, characteristic_map]
      have eq_b_to_cb: @b_to_cb (dim_map e') = (congrArg (fun m ↦ (cb m: Type)) dim_eq_np1.symm).mp ∘ (@b_to_cb (n + 1)) ∘ (congrArg (fun m ↦ (b m: Type)) dim_eq_np1).mp := by
        apply @Eq.rec ℕ (dim_map e') (fun p eq ↦ @b_to_cb (dim_map e') = (congrArg (fun m ↦ (cb m: Type)) eq.symm).mp ∘ (@b_to_cb p) ∘ (congrArg (fun m ↦ (b m: Type)) eq).mp) rfl
        exact dim_eq_np1
      have eq_cast:  (congrArg (fun m ↦ (cb m: Type)) ind_eq_np1).mp ∘ (congrArg (fun m ↦ (cb m: Type)) (dim_map_indices_to_nat_comm e').symm).mp ∘ (congrArg (fun m ↦ (cb m: Type)) dim_eq_np1.symm).mp = id := by
        funext y
        simp
      have eq_ind_to_cb_to_X: (indices_to_cb_to_X (cell_to_indices e')) = (indices_to_cb_to_X (Sum.inr ⟨n, i⟩)) ∘ (congrArg (fun ind ↦ (cb (indices_to_Nat ind): Type)) ind_eq).mp := by
        apply @Eq.rec _ (cell_to_indices e') (fun ind' ind_eq' ↦ (indices_to_cb_to_X (cell_to_indices e')) = (indices_to_cb_to_X (ind')) ∘ (congrArg (fun ind ↦ (cb (indices_to_Nat ind): Type)) ind_eq').mp) rfl
        exact ind_eq
      calc
        (indices_to_cb_to_X (cell_to_indices e')) ∘ (congrArg (fun m ↦ (cb m: Type)) (dim_map_indices_to_nat_comm e').symm).mp ∘ b_to_cb = (indices_to_cb_to_X (Sum.inr ⟨n, i⟩)) ∘ (congrArg (fun ind ↦ (cb (indices_to_Nat ind): Type)) ind_eq).mp ∘ (congrArg (fun m ↦ (cb m: Type)) (dim_map_indices_to_nat_comm e').symm).mp ∘ b_to_cb := by
          rw [eq_ind_to_cb_to_X]
          rfl
        _ = (indices_to_cb_to_X (Sum.inr ⟨n, i⟩)) ∘ (congrArg (fun m ↦ (cb m: Type)) ind_eq_np1).mp ∘ (congrArg (fun m ↦ (cb m: Type)) (dim_map_indices_to_nat_comm e').symm).mp ∘ (congrArg (fun m ↦ (cb m: Type)) dim_eq_np1.symm).mp ∘ (@b_to_cb (n + 1)) ∘ (congrArg (fun m ↦ (b m: Type)) dim_eq_np1).mp := by rw [eq_b_to_cb]
        _ = (indices_to_cb_to_X (Sum.inr ⟨n, i⟩)) ∘ ((congrArg (fun m ↦ (cb m: Type)) ind_eq_np1).mp ∘ (congrArg (fun m ↦ (cb m: Type)) (dim_map_indices_to_nat_comm e').symm).mp ∘ (congrArg (fun m ↦ (cb m: Type)) dim_eq_np1.symm).mp) ∘ (@b_to_cb (n + 1)) ∘ (congrArg (fun m ↦ (b m: Type)) dim_eq_np1).mp := by funext y; simp
        _ = (indices_to_cb_to_X (Sum.inr ⟨n, i⟩)) ∘ id ∘ (@b_to_cb (n + 1)) ∘ (congrArg (fun m ↦ (b m: Type)) dim_eq_np1).mp := by rw [eq_cast]
        _ = (indices_to_cb_to_X (Sum.inr ⟨n, i⟩)) ∘ (@b_to_cb (n + 1)) ∘ (congrArg (fun m ↦ (b m: Type)) dim_eq_np1).mp := by funext y; simp
        _ = h ∘ g := by
          simp [indices_to_cb_to_X, h, g, right_adj_proj, f]
          funext y
          rfl
    rw [aux_decomp]
    exact h_inducing.comp g_inducing

theorem characteristic_map_inner_embedding: ∀ e:(cell_sets (CWC := CWC)), Topology.IsEmbedding (cb_inner_map (characteristic_map e)) := by
  intro e
  rw [Topology.isEmbedding_iff]
  exact ⟨characteristic_map_inducing_on_inner e, characteristic_map_inj_on_inner e⟩

lemma skn_sub_cell_iunion (n: ℕ): CWC.Fsk n ⊆ ⋃ p:cell_sets, ⋃ _: (dim_map p < (n + 1)), p.1 := by
  induction' n with n ih
  case zero =>
    intro x hx
    have x_in_cells: {x} ∈ cell_sets := by
      exact cell_of_dim0_in_sets' x hx
    simp
    use {x}
    constructor
    . use cell_of_dim0_in_sets' x hx
      apply dim_map_cell_dim0_is_0
      use x
    . rfl
  case succ =>
    intro x hx
    rcases Classical.em (x ∈ Fsk (n)) with x_in_skn | x_not_in_skn
    . have hsub: (⋃ p:cell_sets, ⋃ _:(dim_map p < n + 1), p.1) ⊆ (⋃ p:(cell_sets (CWC := CWC)), ⋃ _:(dim_map p < n + 1 + 1), p.1) := by
        intro t ht
        simp at ht
        rcases ht with ⟨e, ⟨e_in_sets, dim_e_lt_np1⟩, t_in_e⟩
        simp
        use e
        constructor
        . use e_in_sets
          linarith
        . exact t_in_e
      exact hsub (ih x_in_skn)
    . rcases mem_cell_in_adj_sk x_not_in_skn hx with ⟨i, x_in_cell_ni⟩
      simp
      use (Set.range (cell_define_map n i))
      constructor
      . use cell_define_map_range_in_sets n i
        rw [dim_map_cell_n_is_np1]
        linarith
      . exact x_in_cell_ni

theorem characteristic_map_boundary: ∀ e:(cell_sets (CWC := CWC)), Set.range (cb_boundary_map (characteristic_map e)) ⊆ ⋃ p:cell_sets, ⋃ _:(dim_map p < dim_map e), p.1 := by
  rintro ⟨e, e_in_sets⟩
  rw [boundary_map_range]
  rcases e_in_sets with ⟨e_in_sk0|e_in_skn, e_nonempty⟩
  . rcases e_in_sk0 with ⟨x, x_in_sk0, rfl⟩
    let e' : cell_sets := ⟨{x},  ⟨Or.inl (Exists.intro x ⟨x_in_sk0, Eq.refl {x}⟩), e_nonempty⟩⟩
    have dim_eq_0: dim_map e' = 0 := by
      rw [dim_map_cell_dim0_is_0]
      use x
    have boundary_empty: @cb_boundary (dim_map e') = ∅ := by
      simp [←cb_cast_mp_boundary_eq_boundary dim_eq_0.symm, cb0_boundary_empty]
    simp [boundary_empty]
  . rw [Set.mem_iUnion] at e_in_skn
    rcases e_in_skn with ⟨n, ⟨i, heq⟩⟩
    simp at heq
    rw [characteristic_map, Set.image_comp, cb_cast_mp_boundary_eq_boundary (by rw [dim_map_indices_to_nat_comm])]
    let e' : cell_sets := ⟨e, ⟨Or.inr e_in_skn, e_nonempty ⟩⟩
    have ind_eq: cell_to_indices e' = Sum.inr ⟨n, i⟩ := by simp [e', ←heq, cell_to_indices_on_dimn_cell]
    have dim_eq: dim_map e' = (n + 1) := by simp [e', ←heq]; rw [dim_map_cell_n_is_np1]
    rw [ind_eq, indices_to_cb_to_X]
    let A := {(x: Σ_:(CWC.Fι n), cb (n + 1)) | x.2 ∈ cb_boundary}
    have image_sub: Sigma.mk i '' cb_boundary ⊆ A := by rw [Set.image_subset_iff]; exact fun ⦃a⦄ a ↦ a
    calc
      Subtype.val ∘ (CWC.Fφ n) ∘ (adj_proj _ (CWC.Ff n)) ∘ Sum.inr ∘ Sigma.mk i '' cb_boundary = (Subtype.val ∘ (CWC.Fφ n) ∘ (adj_proj _ (CWC.Ff n)) ∘ Sum.inr) ∘ Sigma.mk i '' cb_boundary := by simp
      _ = (Subtype.val ∘ (CWC.Fφ n) ∘ (adj_proj _ (CWC.Ff n)) ∘ Sum.inr) '' (Sigma.mk i '' cb_boundary) := by rw [Set.image_comp]
      _ ⊆ (Subtype.val ∘ (CWC.Fφ n) ∘ (adj_proj _ (CWC.Ff n)) ∘ Sum.inr) '' A := Set.image_mono image_sub
      _ = ((Subtype.val ∘ (CWC.Fφ n)) ∘ ((adj_proj _ (CWC.Ff n)) ∘ Sum.inr)) '' A := by simp
      _ = (Subtype.val ∘ (CWC.Fφ n)) '' (((adj_proj _ (CWC.Ff n)) ∘ Sum.inr) '' A) := by rw [Set.image_comp]
      _ ⊆ (Subtype.val ∘ (CWC.Fφ n)) '' (Set.range (left_adj_proj _ (CWC.Ff n))) := by apply Set.image_mono; apply left_range_cover_glue_image
      _ = Set.range ((Subtype.val ∘ (CWC.Fφ n)) ∘ (left_adj_proj _ (CWC.Ff n))) := by rw [←Set.range_comp]
      _ = Set.range (Subtype.val ∘ ((CWC.Fφ n) ∘ (left_adj_proj _ (CWC.Ff n)))) := by rfl
      _ = Set.range (Subtype.val ∘ fun x:CWC.Fsk n ↦ ⟨x.1, (CWC.Fsk_chain n x.2)⟩) := by rw [CWC.Fφ_fix]
      _ = CWC.Fsk n := by ext x; simp
      _ ⊆ ⋃ p: cell_sets (CWC:=CWC), ⋃ _:(dim_map p < dim_map e'), p.1 := by rw [dim_eq]; exact skn_sub_cell_iunion n

def point_indices := (CWC.Fsk 0) ⊕ (Σ(n:ℕ), Σ(_: CWC.Fι n), b (n + 1))

def pid_to_pt : (point_indices (CWC := CWC)) → X := fun I ↦ match I with
| Sum.inl ⟨x, _⟩ => x
| Sum.inr ⟨n, i, y⟩ => cell_define_map n i y

lemma pid_to_pt_inl_ne_inr {x₀: X} (hx₀: x₀ ∈ CWC.Fsk 0) {n: ℕ} (i: CWC.Fι n) (y: b (n + 1)): pid_to_pt (Sum.inl ⟨x₀, hx₀⟩) ≠ pid_to_pt (Sum.inr ⟨n, i, y⟩) := by
  simp only [pid_to_pt]
  let e := Set.range (cell_define_map n i)
  have : cell_define_map n i y ∈ (Set.range (cell_define_map n i)) := by
    exact Set.mem_range_self y
  refine Disjoint.ne_of_mem ?_ hx₀ (Set.mem_range_self y)
  exact Fsk_0_cell_disjoint n i

lemma pid_to_pt_injective: Function.Injective (pid_to_pt (CWC := CWC)) := by
  intro p₁ p₂ hp₁p₂
  match p₁ with
  | Sum.inl ⟨x₁, hx₁⟩ =>
    match p₂ with
    | Sum.inl ⟨x₂, hx₂⟩ =>
      simp [pid_to_pt] at hp₁p₂
      congr
    | Sum.inr ⟨n₂, i₂, x₂⟩ =>
      let hne := pid_to_pt_inl_ne_inr hx₁ i₂ x₂
      contradiction
  | Sum.inr ⟨n₁, i₁, x₁⟩ =>
    match p₂ with
    | Sum.inl ⟨x₂, hx₂⟩ =>
      let hne := (pid_to_pt_inl_ne_inr hx₂ i₁ x₁).symm
      contradiction
    | Sum.inr ⟨n₂, i₂, x₂⟩ =>
      simp [pid_to_pt] at hp₁p₂
      rcases eq_or_ne n₁ n₂ with n₁_eq_n₂ | n₁_ne_n₂
      . let i₁_congr := fun {t:ℕ} (ht: n₁ = t) ↦ (congrArg CWC.Fι ht).mp i₁
        let x₁_congr := fun {t:ℕ} (ht: n₁ = t) ↦ (congrArg (fun m:ℕ ↦ (b (m + 1):Type)) ht).mp x₁
        rw [Eq.rec (motive := fun (t:ℕ) (ht: n₁ = t) ↦ cell_define_map n₁ i₁ x₁ = cell_define_map t (i₁_congr ht) (x₁_congr ht)) rfl n₁_eq_n₂] at hp₁p₂
        rw [Eq.rec (motive := fun (t:ℕ) (ht: n₁ = t) ↦ (Sum.inr ⟨n₁, i₁, x₁⟩:point_indices) = Sum.inr ⟨t, (i₁_congr ht), (x₁_congr ht)⟩) rfl  n₁_eq_n₂]
        rcases eq_or_ne (i₁_congr n₁_eq_n₂) i₂ with i₁'_eq_i₂ | i₁'_ne_i₂
        . sorry
        . have: cell_define_map n₂ (i₁_congr n₁_eq_n₂) (x₁_congr n₁_eq_n₂) ≠ cell_define_map n₂ i₂ x₂ := by
            refine Disjoint.ne_of_mem ?_ (Set.mem_range_self (x₁_congr n₁_eq_n₂)) (Set.mem_range_self x₂)
            exact cell_of_same_n_different_i_disjoint n₂ (i₁_congr n₁_eq_n₂) i₂ i₁'_ne_i₂
          contradiction
      . have: cell_define_map n₁ i₁ x₁ ≠ cell_define_map n₂ i₂ x₂ := by
          refine Disjoint.ne_of_mem ?_ (Set.mem_range_self x₁) (Set.mem_range_self x₂)
          exact cell_of_different_n_disjoint n₁ i₁ n₂ i₂ n₁_ne_n₂
        contradiction

def pid_to_nat : (point_indices (CWC := CWC)) → ℕ := fun I ↦ match I with
| Sum.inl _ => 0
| Sum.inr ⟨n, _⟩ => n + 1

lemma pid_to_pt_in_sk: ∀ p:(point_indices (CWC := CWC)), pid_to_pt p ∈ CWC.Fsk (pid_to_nat p) := by
  intro p
  match p with
  | Sum.inl x => simp [pid_to_pt]
  | Sum.inr ⟨n, i, y⟩ =>
    simp [pid_to_pt, pid_to_nat]
    apply cell_n_in_Fsk_np1 n i
    use y

open Classical

noncomputable def direct_sum_to_R {n: ℕ} (i: CWC.Fι n) (p: cb (n + 1)): ((CWC.Fsk n) ⊕ (Σ_:(CWC.Fι n), cb (n + 1))) → ℝ := fun I ↦ match I with
| Sum.inl _ => 1
| Sum.inr ⟨i', x⟩ => if i' ≠ i then 1 else (sep_fun p.1 (cb (n + 1)) x.1)

lemma direct_sum_to_R_on_boundary_eq_1 {n: ℕ} (i: CWC.Fι n) (p: cb (n + 1)) (hp: p ∈ cb_inner): ∀ y ∈ {x : (Σ_:(CWC.Fι n), cb (n + 1)) | x.2 ∈ cb_boundary}, direct_sum_to_R i p (Sum.inr y) = 1 := by
  intro y hy
  rcases eq_or_ne y.1 i with y_fst_eq_i | y_fst_ne_i
  . simp [direct_sum_to_R, y_fst_eq_i]
    rw [sep_fun_cb_eq_1_iff hp]
    rcases hy with ⟨z, hz⟩
    simp [←hz]
  . simp [direct_sum_to_R, y_fst_ne_i]

lemma direct_sum_to_R_factors {n: ℕ} (i: CWC.Fι n) (p: cb (n + 1)) (hp: p ∈ cb_inner): ∀ x₁ x₂: ((CWC.Fsk n) ⊕ (Σ_:(CWC.Fι n), cb (n + 1))),
    glue_setoid _ (CWC.Ff n) x₁ x₂ → direct_sum_to_R i p x₁ = direct_sum_to_R i p x₂ := by
  intro x₁ x₂ hx₁x₂
  rcases glue_rel_equiv_explicit _ _ x₁ x₂ hx₁x₂ with c₀ | c₁ | c₂ | c₃ | c₄
  . rcases c₀ with ⟨x, hx, rfl⟩; rfl
  . rcases c₁ with ⟨x, y, y', hx, hy, hy', heq⟩
    rw [hy, hy', direct_sum_to_R_on_boundary_eq_1 _ _ hp y'.1 y'.2, hx, direct_sum_to_R]
  . rcases c₂ with ⟨y, x, y', hy, hx, hy', heq⟩
    rw [hy, hy', direct_sum_to_R_on_boundary_eq_1 _ _ hp y'.1 y'.2, hx, direct_sum_to_R]
  . rcases c₃ with ⟨y₁, y₂, y₁', y₂', hy₁, hy₂, hy₁', hy₂', hy₁'y₂', y₁_ne_y₂⟩
    rw [hy₁, hy₂, ←hy₁', ←hy₂', direct_sum_to_R_on_boundary_eq_1 _ _ hp y₁'.1 y₁'.2, direct_sum_to_R_on_boundary_eq_1 _ _ hp y₂'.1 y₂'.2]
  . rcases c₄ with ⟨_, _, heq⟩
    rw [heq]

instance instNonemptyConstructorFsk {n: ℕ}: Nonempty (CWC.Fsk n) := by
  rcases CWC.Fsk0_nonempty with ⟨x, hx⟩
  use x
  exact Fsk_incl (m := 0) (by norm_num) hx
instance instNonemptyConstructorAdjointSpace {n: ℕ}: Nonempty (AdjointSpace _ (CWC.Ff n)) := by
  infer_instance

noncomputable def pid_to_sk_to_R: (p: point_indices (CWC := CWC)) → CWC.Fsk (pid_to_nat p) → ℝ := fun I ↦ match I with
| Sum.inl x => fun y ↦ if y = x then 0 else 1
| Sum.inr ⟨n, i, x⟩ => (Quotient.lift (direct_sum_to_R i (b_to_cb x)) (direct_sum_to_R_factors i (b_to_cb x) (by use x))) ∘ (Function.invFun (CWC.Fφ n))

theorem pid_to_sk_R_continuous {p: point_indices (CWC := CWC)} : Continuous (pid_to_sk_to_R p) := by
  match p with
  | Sum.inl x =>
    simp [pid_to_sk_to_R]
    have: DiscreteTopology (CWC.Fsk (pid_to_nat (Sum.inl x))) := CWC.Tsk0_discrete
    exact continuous_of_discreteTopology
  | Sum.inr ⟨n, i, x⟩ =>
    dsimp only [pid_to_sk_to_R]
    apply Continuous.comp
    . apply Continuous.quotient_lift
      rw [continuous_sum_dom]
      constructor
      . have : (direct_sum_to_R i (b_to_cb x) ∘ Sum.inl) = fun _ ↦ 1 := by ext z; simp [direct_sum_to_R]
        rw [this]
        exact continuous_const
      . rw [continuous_sigma_iff]
        intro i₀
        rcases eq_or_ne i₀ i with i₀_eq_i | i₀_ne_i
        . have: (fun a ↦ (direct_sum_to_R i (b_to_cb x) ∘ Sum.inr) ⟨i₀, a⟩) = (sep_fun x.1 (cb (n + 1))) ∘ Subtype.val := by ext y; simp [direct_sum_to_R, i₀_eq_i]
          rw [this]
          apply Continuous.comp
          . apply sep_fun_cont (by norm_num) (convex_closedBall 0 1) (by apply isCompact_closedBall)
            rw [interior_closedBall' 0 1]
            exact x.2
          . exact continuous_subtype_val
        . have: (fun a ↦ (direct_sum_to_R i (b_to_cb x) ∘ Sum.inr) ⟨i₀, a⟩) = fun _ ↦ 1 := by ext y; simp [direct_sum_to_R, i₀_ne_i]
          rw [this]
          exact continuous_const
    . let Fφ_heom := CWC.Fφ_heomorph n
      rw [isHomeomorph_iff_exists_inverse] at Fφ_heom
      rcases Fφ_heom with ⟨Fφ_cont, g, g_left_inv, g_right_inv, g_cont⟩
      have: g = Function.invFun (CWC.Fφ n) := by
        ext y
        suffices CWC.Fφ n (g y) = (CWC.Fφ n) (Function.invFun (CWC.Fφ n) y) by
          exact g_left_inv.injective this
        rw [g_right_inv, Function.invFun_eq ⟨g y, g_right_inv y⟩]
      rwa [←this]

theorem pid_to_sk_to_R_eq_0_iff (p: point_indices (CWC := CWC)): ∀ x, pid_to_sk_to_R p x = 0 ↔ x = ⟨pid_to_pt p, pid_to_pt_in_sk p⟩ := by
  intro x
  refine Iff.intro ?mp ?mpr
  case mp =>
    intro hx
    match p with
    | Sum.inl x₀ =>
      simp [pid_to_sk_to_R] at hx
      simpa [pid_to_pt] using hx
    | Sum.inr ⟨n, i, xn⟩ =>
      simp [pid_to_sk_to_R] at hx
      let x' := Function.invFun (CWC.Fφ n) x
      rcases Quotient.exists_rep x' with ⟨x'_rep, rep_eq⟩
      have hrep: direct_sum_to_R i (b_to_cb xn) x'_rep = 0 := by
        have : Quotient.lift (direct_sum_to_R i (b_to_cb xn)) (direct_sum_to_R_factors i (b_to_cb xn) (by use xn)) x' = 0 := hx
        rwa [←rep_eq] at this
      match x'_rep with
      | Sum.inl rep_left => simp [direct_sum_to_R] at hrep
      | Sum.inr ⟨i₁, x₁⟩=>
        rcases eq_or_ne i₁ i with i₁_eq_i | i₁_ne_i
        . simp [direct_sum_to_R, i₁_eq_i] at hrep
          rw [sep_fun_eq_0_iff (by apply isCompact_closedBall) (by rw [cb, interior_closedBall' 0 1]; exact xn.2)] at hrep
          simp [pid_to_pt, cell_define_map, pre_characteristic_map, ←hrep]
          have : adj_proj _ (CWC.Ff n) (Sum.inr ⟨i, x₁⟩) = x' := by rw [←rep_eq, i₁_eq_i]; rfl
          rw [this]
          unfold x'; apply Eq.symm
          apply Function.invFun_eq
          apply (CWC.Fφ_heomorph n).surjective
        . simp [direct_sum_to_R, i₁_ne_i] at hrep
  case mpr =>
    intro hx
    match p with
    | Sum.inl x₀ =>
      simpa [pid_to_sk_to_R] using hx
    | Sum.inr ⟨n, i, xn⟩ =>
      simp [pid_to_sk_to_R]
      simp [pid_to_pt, cell_define_map, pre_characteristic_map] at hx
      rw [hx]
      show Quotient.lift (direct_sum_to_R i ⟨xn, b_in_cb xn.2⟩) (direct_sum_to_R_factors i ⟨xn.1, b_in_cb xn.2⟩ (by use xn; rfl))
        ((Function.invFun (CWC.Fφ n) ∘ CWC.Fφ n) ((adj_proj _ (CWC.Ff n) (Sum.inr ⟨i, ⟨xn, b_in_cb xn.2⟩⟩)))) = 0
      rw [Function.invFun_comp (CWC.Fφ_heomorph n).injective]
      have: Quotient.lift (direct_sum_to_R i ⟨xn, b_in_cb xn.2⟩) (direct_sum_to_R_factors i ⟨xn.1, b_in_cb xn.2⟩ (by use xn; rfl)) ((adj_proj _ (CWC.Ff n) (Sum.inr ⟨i, ⟨xn, b_in_cb xn.2⟩⟩))) = (direct_sum_to_R i ⟨xn, b_in_cb xn.2⟩) (Sum.inr ⟨i, ⟨xn, b_in_cb xn.2⟩⟩) := by rfl
      simp [this, direct_sum_to_R]
      rw [sep_fun_eq_0_iff (by apply isCompact_closedBall) (by rw [cb, interior_closedBall' 0 1]; exact xn.2)]

noncomputable def direct_sum_to_R_extension {n: ℕ} (fn: CWC.Fsk n → ℝ): ((CWC.Fsk n) ⊕ (Σ_:(CWC.Fι n), cb (n + 1))) → ℝ := fun I ↦ match I with
| Sum.inl x => fn x
| Sum.inr ⟨i, x⟩ => cb_extension (Nat.le_add_left 1 n) (fun z:(@cb_boundary (n + 1)) ↦ fn (CWC.Ff n ⟨⟨i, z.1 ⟩, z.2⟩)) x

lemma direct_sum_to_R_extension_factors {n: ℕ} (fn: CWC.Fsk n → ℝ): ∀ x₁ x₂: ((CWC.Fsk n) ⊕ (Σ_:(CWC.Fι n), cb (n + 1))),
    glue_setoid _ (CWC.Ff n) x₁ x₂ → direct_sum_to_R_extension fn x₁ = direct_sum_to_R_extension fn x₂ := by
  intro x₁ x₂ hx₁x₂
  rcases glue_rel_equiv_explicit _ _ x₁ x₂ hx₁x₂ with c₀ | c₁ | c₂ | c₃ | c₄
  . rcases c₀ with ⟨x, hx, rfl⟩; rfl
  . rcases c₁ with ⟨x, y, y', hx, hy, hy', heq⟩
    simp [hx, hy, direct_sum_to_R_extension, hy', cb_extension_eq_on_boundary (Nat.le_add_left 1 n) _ _ y'.2, heq]
  . rcases c₂ with ⟨y, x, y', hy, hx, hy', heq⟩
    simp [hx, hy, direct_sum_to_R_extension, hy', cb_extension_eq_on_boundary (Nat.le_add_left 1 n) _ _ y'.2, heq]
  . rcases c₃ with ⟨y₁, y₂, y₁', y₂', hy₁, hy₂, hy₁', hy₂', hy₁'y₂', y₁_ne_y₂⟩
    simp [hy₁, hy₂, direct_sum_to_R_extension, ←hy₁', ←hy₂']
    simp [cb_extension_eq_on_boundary (Nat.le_add_left 1 n) _ _ y₁'.2, cb_extension_eq_on_boundary (Nat.le_add_left 1 n) _ _ y₂'.2, hy₁'y₂']
  . rcases c₄ with ⟨y, hy, rfl⟩; rfl

noncomputable def pid_to_sk_chain_to_R (p: point_indices (CWC := CWC)) : (n: ℕ) → CWC.Fsk (pid_to_nat p + n) → ℝ := fun n ↦ match n with
| 0 => pid_to_sk_to_R p
| Nat.succ n => Quotient.lift (direct_sum_to_R_extension (pid_to_sk_chain_to_R p n)) (direct_sum_to_R_extension_factors (pid_to_sk_chain_to_R p n)) ∘ (Function.invFun (CWC.Fφ (pid_to_nat p + n)))

end CWComplexConstructor
end

end Chp5

section
variable {X: Type*} [TopologicalSpace X]
instance (h: ∀p:X, ∃ (f: X → ℝ), Continuous f ∧ f ⁻¹' ({0}) = {p}) : T2Space X := by
  refine { t2 := ?_ }
  intro x y x_ne_y
  rcases h x with ⟨f, f_cont, hf⟩
  have fx_eq_0: f x = 0 := by
    have : x ∈ ({x}: Set X) := by rfl
    rw [←hf] at this
    exact this
  have fy_ne_0: f y ≠ 0 := by
    by_contra! fy_eq_0
    have : y ∈ f ⁻¹' {0} := by exact fy_eq_0
    rw [hf] at this
    have: x = y := by exact this.symm
    contradiction
  have fx_ne_fy: f x ≠ f y := ne_of_eq_of_ne fx_eq_0 (id (Ne.symm fy_ne_0))
  rcases t2_separation fx_ne_fy with ⟨u', v', u'_open, v'_open, fx_in_u', fy_in_v', u'_v'_disjoint⟩
  let u := f ⁻¹' u'
  let v := f ⁻¹' v'
  have u_open: IsOpen u := by exact f_cont.isOpen_preimage u' u'_open
  have v_open: IsOpen v := by exact f_cont.isOpen_preimage v' v'_open
  have x_in_u: x ∈ u := fx_in_u'
  have y_in_v: y ∈ v := fy_in_v'
  have uv_disj: Disjoint u v := by exact Disjoint.preimage f u'_v'_disjoint
  use u, v
end

section
variable {X: Type*}
example {s₁ s₂: Set X} (h: Disjoint s₁ s₂) {x₁ x₂: X} (h₁: x₁ ∈ s₁) (h₂: x₂ ∈ s₂): x₁ ≠ x₂ := by
  exact Disjoint.ne_of_mem h h₁ h₂
end
