import STCC.TopologicalProperties
import Mathlib.Order.WellFounded

open BigOperators
namespace Chp5
open CellComplexClass

section
variable {X: Type*} [T: TopologicalSpace X] [T2Space X] [C: CellComplexClass X] [CW: CWComplexClass X]
-- a direct proof of 5.17
theorem quotient_sigma_cb_map : Topology.IsQuotientMap (fun (⟨e, d⟩: (_:C.sets) × cb (C.dim_map _)) ↦ C.characteristic_map e d) where
  surjective := by
    intro x
    simp
    rcases exists_mem_of_cell x with ⟨e, e_in_sets, x_in_e⟩
    use e, e_in_sets
    have : x ∈ Set.range (C.characteristic_map ⟨e, e_in_sets⟩) := by
      rw [characteristic_map_range]
      apply subset_closure
      exact x_in_e
    rw [Set.mem_range] at this
    rcases this with ⟨y, hy⟩
    use y.1, y.2
  eq_coinduced := by
    rw [TopologicalSpace.ext_iff]
    intro s
    let φ := fun (⟨e, d⟩: (_:C.sets) × cb (C.dim_map _)) ↦ C.characteristic_map e d
    show @IsOpen X T s ↔ @IsOpen X (TopologicalSpace.coinduced φ instTopologicalSpaceSigma) s
    have : @IsOpen X (TopologicalSpace.coinduced φ instTopologicalSpaceSigma) s ↔ IsOpen (φ ⁻¹' s) := by rfl
    rw [this, isOpen_sigma_iff]
    simp only [Set.preimage_preimage, φ]
    refine Iff.intro ?mp ?mpr
    case mp =>
      intro s_open_in_X e
      apply Continuous.isOpen_preimage ?_ s s_open_in_X
      exact characteristic_map_continuous e
    case mpr=>
      intro h
      rw [CW.coeherent.open_crit]
      rintro _ ⟨e, e_in_sets, rfl⟩
      let f : cb (C.dim_map ⟨e, e_in_sets⟩) → (closure e) := by
        intro d
        use C.characteristic_map ⟨e, e_in_sets⟩ d
        show characteristic_map ⟨e, e_in_sets⟩ d ∈ closure (⟨e, e_in_sets⟩:C.sets).1
        rw [←characteristic_map_range]
        exact Set.mem_range_self d
      let g : (closure e) → X := (↑)
      have f_cont: Continuous f := by
        -- this refine is generated by apply?
        refine
          Continuous.subtype_mk ?_ fun x ↦
            id
              (Eq.mpr
                (id
                  (congrArg (fun _a ↦ characteristic_map ⟨e, e_in_sets⟩ x ∈ _a)
                    (Eq.symm (characteristic_map_range ⟨e, e_in_sets⟩))))
                (Set.mem_range_self x))
        exact characteristic_map_continuous ⟨e, e_in_sets⟩
      have : Topology.IsQuotientMap f := by
        apply IsClosedMap.isQuotientMap (Continuous.isClosedMap f_cont) f_cont
        rintro ⟨x, x_in_ce⟩
        simp [f]
        rw [←characteristic_map_range' e e_in_sets, Set.mem_range] at x_in_ce
        rcases x_in_ce with ⟨y, hy⟩
        use y.1, y.2
      rw [←Topology.IsQuotientMap.isOpen_preimage this]
      rw [Set.preimage_preimage]
      apply h

def CellAttached_boundary {n: ℕ} {ι: Type*} : Set (Σ_: ι, cb n) := {x | x.2 ∈ cb_boundary}

def CellAttached_f {n: ℕ} {ι: Type*} {S: Set X} (g: ι → cb n → X) (hg: ∀ i:ι, ∀ x:cb n, x ∈ cb_boundary →  g i x ∈ S) : @CellAttached_boundary n ι → S := fun x ↦ ⟨g x.1.1 x.1.2, hg x.1.1 x.1.2 x.2⟩

def CellAttached {n: ℕ} {ι: Type*} {S: Set X} (g: ι → cb n → X) (hg: ∀ i:ι, ∀ x:cb n, x ∈ cb_boundary →  g i x ∈ S) :=
  AdjointSpace CellAttached_boundary (CellAttached_f g hg)

instance {n: ℕ} {ι: Type*} {S: Set X} (g: ι → cb n → X) (hg: ∀ i:ι, ∀ x:cb n, x ∈ cb_boundary →  g i x ∈ S) : TopologicalSpace (CellAttached g hg)  := by
  rw [CellAttached]
  infer_instance

def CellOfDim (n: ℕ) := {e: C.sets | C.dim_map e = n}

def characteristic_cn (n: ℕ) : @CellOfDim X _ _ C n → cb n → X := fun ⟨e, he⟩ x ↦ C.characteristic_map e ((congrArg (fun p ↦ (cb p: Type)) he.symm).mp x)

-- example usage of Eq.rec and congArg
-- example {f : ℕ → Type} (n1 n2: ℕ) (h: n1 = n2) : f n1 = f n2 := by
--   exact congrArg f h
-- example {f: ℕ → Type} {g: (n: ℕ) → Set (f n)}{n1 n2: ℕ} (eq: n1 + 1 = n2) (x: f (n1 + 1)) (h: x ∈ g (n1 + 1)): (congrArg f eq).mp x ∈ g n2 :=
--   Eq.rec (motive := fun n2' eq' => (congrArg f eq').mp x ∈ g n2') h eq

omit CW in theorem char_cnp1_boundary_in_skn (n: ℕ): ∀ e: CellOfDim (n + 1), ∀ x: (cb (n + 1)), x ∈ cb_boundary → (characteristic_cn (n + 1) e x) ∈ Skeleton X n := by
  rintro ⟨e, he⟩ x x_in_boundary
  have mem_0: characteristic_cn (n + 1) ⟨e, he⟩ x ∈ Set.range (cb_boundary_map (C.characteristic_map e)) := by
    rw [characteristic_cn]
    apply mem_boundary_map_range_of_mem_boundary
    apply @Eq.rec ℕ (n + 1) (fun (n':ℕ) (eq:(n + 1 = n')) ↦ (congrArg (fun p ↦ (cb p:Type)) eq.symm).mpr x ∈ @cb_boundary n') x_in_boundary _ (he.symm)
  have mem_1: Set.range (cb_boundary_map (C.characteristic_map e)) ⊆ ⋃p:sets, ⋃_:(C.dim_map p < C.dim_map e), p.1 := C.characteristic_map_boundary e
  have mem_2: ⋃p:sets, ⋃_:(C.dim_map p < C.dim_map e), p.1 ⊆ Skeleton X n := by
    rw [Set.iUnion₂_subset_iff]
    intro p hp
    rw [he] at hp
    rw [sub_skeleton_iff, Nat.le_iff_lt_add_one]
    exact hp
  exact mem_2 (mem_1 mem_0)

def skn_sum_cnp1_to_sknp1 (n: ℕ): (Skeleton X n) ⊕ (Σ_:@CellOfDim X _ _ C (n + 1), cb (n + 1)) → (Skeleton X (n + 1)) := by
  intro x
  match x with
  | Sum.inl ⟨x, x_in_Xn⟩ =>
    exact ⟨x, skeleton_mono n (n + 1) (Nat.le_add_right n 1) x_in_Xn⟩
  | Sum.inr ⟨⟨e, he⟩, x⟩ =>
    use C.characteristic_map e ((congrArg (fun p ↦ (cb p : Type)) he).mpr x)
    suffices Set.range (C.characteristic_map e) ⊆ (Skeleton X (n + 1)) by exact this (Set.mem_range_self _)
    rw [characteristic_map_range]
    apply (Skeleton X (n + 1)).cell_closure_incl e.1 e.2
    show e.1 ⊆ Skeleton X (n + 1)
    rw [sub_skeleton_iff, he]

omit CW in theorem skn_sum_cnp1_to_sknp1_surj {n: ℕ}: Function.Surjective (skn_sum_cnp1_to_sknp1 (C := C) n) := by
  intro x
  rcases exists_mem_of_cell (x:X) with ⟨e, e_in_sets, x_in_e⟩
  have : C.dim_map ⟨e, e_in_sets⟩ ≤ (n + 1) := by
    rw [←sub_skeleton_iff]
    simp
    apply (Skeleton X (n + 1)).subset_of_intersect e_in_sets
    rw [←Set.nonempty_iff_ne_empty]
    use x
    exact ⟨x_in_e, x.2⟩
  match Nat.le_succ_iff.mp this with
  | Or.inl dim_e_le_n =>
    have: (x:X) ∈ (Skeleton X n) := by
      suffices e ⊆ (Skeleton X n) by
        exact this x_in_e
      show (⟨e, e_in_sets⟩:C.sets).1 ⊆ (Skeleton X n)
      rwa [sub_skeleton_iff]
    use Sum.inl ⟨x, this⟩
    rfl
  | Or.inr dim_e_eq_np1 =>
    let e': C.sets := ⟨e, e_in_sets⟩
    have : (x:X) ∈ e'.1 := x_in_e
    rw [←characteristic_map_inner_image] at this
    rcases this with ⟨y, y_in_inner, y_map_to_x⟩
    let f := (congrArg (fun p ↦ (cb p: Type)) dim_e_eq_np1).mp
    let g := (congrArg (fun p ↦ (cb p: Type)) dim_e_eq_np1).mpr
    let y': cb (n + 1) := (congrArg (fun p ↦ (cb p: Type)) dim_e_eq_np1).mp y
    use Sum.inr ⟨⟨e', dim_e_eq_np1⟩, y'⟩
    simp [skn_sum_cnp1_to_sknp1]
    apply SetCoe.ext;simp
    show C.characteristic_map e' (g y') = x
    have : g (f y) = y := by simp [f, g]
    rwa [this]

omit CW in theorem skn_sum_cnp1_to_sknp1_cont {n: ℕ}: Continuous (skn_sum_cnp1_to_sknp1 (C:= C) n) := by
  rw [continuous_sum_dom]
  refine And.intro ?inl_cont ?inr_cont
  case inl_cont =>
    have : skn_sum_cnp1_to_sknp1 n ∘ Sum.inl = fun x ↦ ⟨x.1, skeleton_mono (C:=C) n (n + 1) (Nat.le_add_right n 1) x.2⟩ := by
      ext x
      simp [skn_sum_cnp1_to_sknp1]
    rw [this]
    exact Continuous.subtype_mk continuous_subtype_val fun x ↦ skeleton_mono n (n + 1) (Nat.le_add_right n 1) x.property
  case inr_cont =>
    apply continuous_sigma
    intro e
    simp [skn_sum_cnp1_to_sknp1]
    apply Continuous.subtype_mk
    apply Continuous.comp
    . apply C.characteristic_map_continuous
    exact @Eq.rec ℕ (C.dim_map e.1) (fun n hn ↦ Continuous (congrArg (fun p ↦ (cb p : Type)) hn).mpr) (continuous_id) (n + 1) e.2

omit CW in theorem skn_sum_cnp1_to_sknp1_factors {n: ℕ}: ∀ x₁ x₂: (Skeleton X n) ⊕ (Σ_:CellOfDim (n + 1), cb (n + 1)),
  glue_setoid
    (@CellAttached_boundary (n + 1) (CellOfDim (n + 1)))
    (@CellAttached_f X (n + 1) (CellOfDim (n + 1)) (Skeleton X n) (characteristic_cn (n + 1)) (char_cnp1_boundary_in_skn n))
    x₁ x₂ →
  skn_sum_cnp1_to_sknp1 n x₁ = skn_sum_cnp1_to_sknp1 n x₂ := by
    intro x₁ x₂ h₁₂
    rcases glue_rel_equiv_explicit _ _ x₁ x₂ h₁₂ with c0 | c1 | c2 | c3 | c4
    . rcases c0 with ⟨x, heq1, heq2⟩
      rw [heq2]
    . rcases c1 with ⟨x, y, y', heq1, heq2, heq3, heq4⟩
      rw [CellAttached_f] at heq4
      simp [heq1, skn_sum_cnp1_to_sknp1, heq2, heq4, ←heq3, characteristic_cn]
      rw [←heq3]
    . rcases c2 with ⟨y, x, y', heq1, heq2, heq3, heq4⟩
      rw [CellAttached_f] at heq4
      simp [heq1, skn_sum_cnp1_to_sknp1, heq2, heq4, ←heq3, characteristic_cn]
      rw [←heq3]
    . rcases c3 with ⟨y₁, y₂, y₁', y₂', heq1, heq2, heq3, heq4, heq5, hne⟩
      simp [heq1, heq2, skn_sum_cnp1_to_sknp1]
      simp [CellAttached_f, characteristic_cn, heq3, heq4] at heq5
      rwa [heq3, heq4] at heq5
    . rcases c4 with ⟨y, heq1, heq2⟩
      rw [heq2]

def cell_attached_to_sknp1 (n: ℕ): @CellAttached X (n + 1) _ _ (characteristic_cn (n + 1)) (char_cnp1_boundary_in_skn n) → (Skeleton X (n + 1)) := (Quotient.lift (skn_sum_cnp1_to_sknp1 n) skn_sum_cnp1_to_sknp1_factors)

section helper
variable {X: Type*} [T: TopologicalSpace X] [T2Space X] [C: CellComplexClass X]
theorem mem_boundary_of_same_char_image₁ {n: ℕ} {y₁ y₂: cb (n + 1)} {e₁ e₂: C.sets} (h_e₁_dim: C.dim_map e₁ = n + 1)
    (h_e₂_dim: C.dim_map e₂ = n + 1) (h_ne_y: y₁ ≠ y₂) (e₁_eq_e₂: e₁ = e₂)
    (h_img_eq: C.characteristic_map e₁ ((congrArg (fun p ↦ (cb p : Type)) h_e₁_dim.symm).mp y₁) =
        C.characteristic_map e₂ ((congrArg (fun p ↦ (cb p : Type)) h_e₂_dim.symm).mp y₂)):
    y₁ ∈ cb_boundary ∧ y₂ ∈ cb_boundary := by
        have h_img_eq': C.characteristic_map e₁ ((congrArg (fun p ↦ (cb p : Type)) h_e₁_dim.symm).mp y₁) =
            C.characteristic_map e₁ ((congrArg (fun p ↦ (cb p : Type)) h_e₁_dim.symm).mp y₂) := by
                rw [h_img_eq]
                apply @Eq.rec C.sets e₁
                    (fun (e':C.sets) (h: e₁ = e') ↦
                        C.characteristic_map e' ((congrArg (fun p ↦ (cb p:Type)) ((congrArg C.dim_map h).symm.trans h_e₁_dim).symm).mp y₂) =
                            C.characteristic_map e₁ ((congrArg (fun p ↦ (cb p : Type)) h_e₁_dim.symm).mp y₂))
                    rfl
                exact e₁_eq_e₂
        let f : cb (n + 1) → cb (C.dim_map e₁) := (congrArg (fun p ↦ (cb p : Type)) h_e₁_dim.symm).mp
        let g : cb (C.dim_map e₁) → cb (n + 1) := (congrArg (fun p ↦ (cb p : Type)) h_e₁_dim).mp
        have g_f_inv: ∀ y, g (f y) = y := by
            intro y
            simp [g, f]
        have f_y_in_inner: ∀ y:(cb (n + 1)), y ∈ cb_inner → f y ∈ cb_inner  := by
            intro y hy
            apply @Eq.rec ℕ (n + 1) (fun m hm ↦ (congrArg (fun p ↦ (cb p : Type)) hm).mp y ∈ cb_inner) hy
            exact h_e₁_dim.symm
        have f_y_in_boundary: ∀y:(cb (n + 1)), y ∈ cb_boundary → f y ∈ cb_boundary := by
            intro y hy
            apply @Eq.rec ℕ (n + 1) (fun m hm ↦ (congrArg (fun p ↦ (cb p : Type)) hm).mp y ∈ cb_boundary) hy
            exact h_e₁_dim.symm
        match @cb_decomp (n + 1) y₁ with
        | Or.inl y₁_in_inneer =>
            have f_y₁_in_inner : f y₁ ∈ cb_inner := f_y_in_inner y₁ y₁_in_inneer
            match @cb_decomp (n + 1) y₂ with
            | Or.inl y₂_in_inner =>
                -- try to get a contradiction
                have f_y₂_in_inner : f y₂ ∈ cb_inner := f_y_in_inner y₂ y₂_in_inner
                have : y₁ = y₂ := by
                    rw [←g_f_inv y₁, ←g_f_inv y₂]
                    apply congrArg
                    exact characteristic_map_inj_on_inner e₁ f_y₁_in_inner f_y₂_in_inner h_img_eq'
                contradiction
            | Or.inr y₂_in_boundary =>
                have f_y₂_in_boundary: f y₂ ∈ cb_boundary := f_y_in_boundary y₂ y₂_in_boundary
                have : C.characteristic_map e₁ (f y₁) ≠ C.characteristic_map e₁ (f y₂) := by
                    exact characteristic_map_inner_boundary_ne _ _ _ _ f_y₁_in_inner f_y₂_in_boundary rfl
                contradiction
        | Or.inr y₁_in_boundary =>
            have f_y₁_in_boundary: f y₁ ∈ cb_boundary := f_y_in_boundary y₁ y₁_in_boundary
            match @cb_decomp (n + 1) y₂ with
            | Or.inl y₂_in_inner =>
                have f_y₂_in_inner: f y₂ ∈ cb_inner := f_y_in_inner _ y₂_in_inner
                have: C.characteristic_map e₁ (f y₁) ≠ C.characteristic_map e₁ (f y₂) := by
                    apply Ne.symm
                    exact characteristic_map_inner_boundary_ne _ _ _ _ f_y₂_in_inner f_y₁_in_boundary rfl
                contradiction
            | Or.inr y₂_in_boundary =>
                exact ⟨y₁_in_boundary, y₂_in_boundary⟩

theorem mem_boundary_of_same_char_image₂ {n: ℕ} {y₁ y₂: cb (n + 1)} {e₁ e₂: C.sets} (h_e₁_dim: C.dim_map e₁ = n + 1)
    (h_e₂_dim: C.dim_map e₂ = n + 1) (e₁_ne_e₂: e₁ ≠ e₂)
    (h_img_eq: C.characteristic_map e₁ ((congrArg (fun p ↦ (cb p : Type)) h_e₁_dim.symm).mp y₁) =
        C.characteristic_map e₂ ((congrArg (fun p ↦ (cb p : Type)) h_e₂_dim.symm).mp y₂)):
    y₁ ∈ cb_boundary ∧ y₂ ∈ cb_boundary := by
      let ff : (e:C.sets) → (he: C.dim_map e = n + 1) → cb (n + 1) → cb (C.dim_map e) := fun e he ↦ (congrArg (fun p ↦ (cb p : Type)) he.symm).mp
      have ff_y_in_set: ∀ e:C.sets, ∀ he: (C.dim_map e = n + 1), ∀ sf: ((n:ℕ) → Set (cb n)), ∀ y:cb (n + 1), y ∈ sf (n + 1) → ff e he y ∈ sf (C.dim_map e) := by
        intro e he sf y hy
        apply @Eq.rec ℕ (n + 1) (fun m hm ↦ (congrArg (fun p ↦ (cb p : Type)) hm).mp y ∈ sf m) hy
        exact he.symm
      let y₁' := ff e₁ h_e₁_dim y₁
      let y₂' := ff e₂ h_e₂_dim y₂
      have h_img_eq' : C.characteristic_map e₁ y₁' = C.characteristic_map e₂ y₂' := h_img_eq
      match @cb_decomp (n + 1) y₁ with
      | Or.inl y₁_in_inner =>
        have ff_y₁_in_inner : y₁' ∈ cb_inner := ff_y_in_set e₁ h_e₁_dim @cb_inner y₁ y₁_in_inner
        have cff_y₁_in_e₁: C.characteristic_map e₁ y₁' ∈ e₁.1 := by rw [←characteristic_map_inner_image];use y₁'
        match @cb_decomp (n + 1) y₂ with
        | Or.inl y₂_in_inner =>
          have f_y₂_in_inner : y₂' ∈ cb_inner := ff_y_in_set e₂ h_e₂_dim @cb_inner y₂ y₂_in_inner
          have cff_y₂_in_e₂: C.characteristic_map e₂ y₂' ∈ e₂.1 := by rw [←characteristic_map_inner_image];use y₂'
          rw [←h_img_eq] at cff_y₂_in_e₂
          have : e₁ = e₂ := by
            apply SetCoe.ext
            exact same_cell_of_mem e₁.2 e₂.2 cff_y₁_in_e₁ cff_y₂_in_e₂
          contradiction
        | Or.inr y₂_in_boundary =>
          have ff_y₂_in_boundary : y₂' ∈ cb_boundary := ff_y_in_set e₂ h_e₂_dim @cb_boundary y₂ y₂_in_boundary
          have : C.characteristic_map e₁ y₁' ≠ C.characteristic_map e₂ y₂' := characteristic_map_inner_boundary_ne e₁ e₂ y₁' y₂' ff_y₁_in_inner ff_y₂_in_boundary (h_e₁_dim.trans h_e₂_dim.symm)
          contradiction
      | Or.inr y₁_in_boundary =>
        have ff_y₁_in_boundary : y₁' ∈ cb_boundary := ff_y_in_set e₁ h_e₁_dim @cb_boundary y₁ y₁_in_boundary
        match @cb_decomp (n + 1) y₂ with
        | Or.inl y₂_in_inner =>
          have ff_y₂_in_inner : y₂' ∈ cb_inner := ff_y_in_set e₂ h_e₂_dim @cb_inner y₂ y₂_in_inner
          have : C.characteristic_map e₁ y₁' ≠ C.characteristic_map e₂ y₂' := (characteristic_map_inner_boundary_ne e₂ e₁ y₂' y₁' ff_y₂_in_inner ff_y₁_in_boundary (h_e₂_dim.trans h_e₁_dim.symm)).symm
          contradiction
        | Or.inr y₂_in_boundary =>
          exact ⟨y₁_in_boundary, y₂_in_boundary⟩
end helper

theorem cell_attached_to_sknp1_homeomorphic {n: ℕ} : IsHomeomorph (@cell_attached_to_sknp1 X _ _ _ n) := by
  refine quotient_lift_is_homeomorph _ ?factors ?is_quot
  case factors =>
    intro x₁ x₂ hx₁x₂
    match x₁ with
    | Sum.inl xl₁ =>
      match x₂ with
      | Sum.inl xl₂ =>
        simp [skn_sum_cnp1_to_sknp1] at hx₁x₂
        rw [hx₁x₂]
      | Sum.inr xr₂ =>
        simp [skn_sum_cnp1_to_sknp1] at hx₁x₂
        have : xr₂ ∈ CellAttached_boundary := by
          apply @mem_boundary_of_image_in_skeleton X _ _ _ n xr₂.2 xr₂.1
          case hy => simp [←hx₁x₂]
          case h_e_dim => exact xr₂.1.2
        simp [glue_setoid]
        apply Relation.EqvGen.rel
        rw [glue_rel]
        use ⟨xr₂, this⟩
        simp [CellAttached_f, characteristic_cn, ←hx₁x₂]
    | Sum.inr xr₁ =>
      match x₂ with
      | Sum.inl xl₂ =>
        simp [skn_sum_cnp1_to_sknp1] at hx₁x₂
        simp [glue_setoid]
        apply Relation.EqvGen.symm
        apply Relation.EqvGen.rel
        rw [glue_rel]
        have: xr₁ ∈ CellAttached_boundary := by
          apply @mem_boundary_of_image_in_skeleton X _ _ _ n xr₁.2 xr₁.1
          case hy => simp [hx₁x₂]
          case h_e_dim => exact xr₁.1.2
        use ⟨xr₁, this⟩
        simp [CellAttached_f, characteristic_cn, hx₁x₂]
      | Sum.inr xr₂ =>
        rcases eq_or_ne xr₁ xr₂ with heq | hne
        . exact Quotient.eq''.mp (congrArg Quotient.mk'' (congrArg Sum.inr heq))
        simp [skn_sum_cnp1_to_sknp1] at hx₁x₂
        have: xr₁ ∈ CellAttached_boundary ∧ xr₂ ∈ CellAttached_boundary:= by
          rcases (eq_or_ne xr₁.1 xr₂.1) with heq' | hne'
          . have: xr₁.2 ≠ xr₂.2 := by
              contrapose! hne
              exact Sigma.subtype_ext heq' (congrArg Subtype.val hne)
            exact mem_boundary_of_same_char_image₁ (C:=C) xr₁.1.2 xr₂.1.2 this (congrArg Subtype.val heq') hx₁x₂
          exact mem_boundary_of_same_char_image₂ (C:=C) xr₁.1.2 xr₂.1.2 (Subtype.coe_ne_coe.mpr hne') hx₁x₂
        refine glue_setoid_of_same_image _ _ this.1 this.2 ?heq
        simpa [CellAttached_f, characteristic_cn] using hx₁x₂
  case is_quot =>
    apply quotient_of_saturate_closed_image_closed
    case f_cont => apply skn_sum_cnp1_to_sknp1_cont
    case f_surj => apply skn_sum_cnp1_to_sknp1_surj
    intro S hS SClosed
    rw [is_closed_iff_is_closed_in_ce_less_than_dim]
    intro e h_e_dim
    let g₂ : (Skeleton X (n + 1)) → X := (↑)
    have g₂_inj: Function.Injective g₂ := Subtype.val_injective
    show IsClosed (closure e.1 ∩ g₂ '' (skn_sum_cnp1_to_sknp1 n '' S))
    match Nat.le_succ_iff.mp h_e_dim with
    | Or.inl dim_e_le_n =>
      let g₁ : (Skeleton X n) → X := (↑)
      have : closure e.1 ∩ g₂ '' (skn_sum_cnp1_to_sknp1 n '' S) = closure e.1 ∩ g₁ '' (Sum.inl ⁻¹' S) := by
        ext x
        refine Iff.intro ?mp ?mpr
        case mp =>
          intro hx
          use hx.1
          have ce_sub_Xn : closure e.1 ⊆ (Skeleton X n) := by
            apply (Skeleton X n).cell_closure_incl _ e.2
            show e.1 ⊆ (Skeleton X n)
            rwa [sub_skeleton_iff e]
          use ⟨x, ce_sub_Xn hx.1⟩
          simp [g₁]
          have: ∃ y ∈ S, x = g₂ (skn_sum_cnp1_to_sknp1 n y) := by
            rcases hx.2 with ⟨w, hw, heq1⟩
            rcases hw with ⟨u, hu, heq2⟩
            rw [←heq2] at heq1
            use u, hu, heq1.symm
          rcases this with ⟨t, ht, htx⟩
          have : x = g₂ (skn_sum_cnp1_to_sknp1 n (Sum.inl ⟨x, ce_sub_Xn hx.1⟩)) := by simp [g₂, skn_sum_cnp1_to_sknp1]
          rw [this] at htx
          rw [Set.ext_iff] at hS
          rw [←hS]
          use t, ht, (Subtype.val_injective htx).symm
        case mpr =>
          intro hx
          use hx.1
          rcases hx.2 with ⟨w, inl_w_in_S, hwx⟩
          use skn_sum_cnp1_to_sknp1 n (Sum.inl w), ⟨Sum.inl w, inl_w_in_S, rfl⟩
          simpa [g₂, skn_sum_cnp1_to_sknp1]
      rw [this]
      have : IsClosed (Sum.inl ⁻¹' S) := IsClosed.preimage continuous_inl SClosed
      rw [is_closed_iff_is_closed_in_ce_less_than_dim] at this
      apply this
      exact dim_e_le_n
    | Or.inr dim_e_eq_np1 =>
      -- inclusion map from cb to sum of cb
      let η : cb (n + 1) → (Σ_:CellOfDim (C := C) (n + 1), cb (n + 1)) := fun x ↦ ⟨⟨e, dim_e_eq_np1⟩, x⟩
      have η_continuous: Continuous η := by
        apply continuous_iff_coinduced_le.mpr
        rw [instTopologicalSpaceSigma]
        exact le_iSup_iff.mpr fun b a ↦ a _
      let φ : cb (n + 1) → X := fun x ↦ C.characteristic_map e ((congrArg (fun p ↦ (cb p : Type)) dim_e_eq_np1).mpr x)
      have φ_closed_map: IsClosedMap φ := by
        apply @Eq.rec ℕ (C.dim_map e)
          (fun m hem ↦ IsClosedMap (fun x:cb m ↦ C.characteristic_map e (((congrArg (fun p ↦ (cb p : Type)) hem)).mpr x)))
          (by simp; apply Continuous.isClosedMap (C.characteristic_map_continuous e))
        exact dim_e_eq_np1
      -- we shall be able to prove φ is closed map
      -- but this lemma shall be proved
      have: closure e.1 ∩ g₂ '' (skn_sum_cnp1_to_sknp1 n '' S) = φ '' (η ⁻¹' (Sum.inr ⁻¹' S)) := by
        ext x
        refine Iff.intro ?mp ?mpr
        case mp =>
          rintro ⟨x_in_ce, ⟨_, ⟨w, w_in_S, rfl⟩, rfl⟩⟩
          rw [←characteristic_map_range, Set.mem_range] at x_in_ce
          rcases x_in_ce with ⟨y, hy⟩
          rw [←hy]
          let p := (congrArg (fun p ↦ (cb p : Type)) dim_e_eq_np1).mp y
          have hp: φ p = C.characteristic_map e y := by simp [φ, p]
          rw [←hp]
          rw [hy] at hp
          use p
          have hp': g₂ (skn_sum_cnp1_to_sknp1 n (Sum.inr (η p))) = φ p := by simp [φ, skn_sum_cnp1_to_sknp1, η, g₂]
          have hp_in_S: Sum.inr (η p) ∈ S := by
            rw [←hS]
            use w, w_in_S
            apply g₂_inj
            rw [←hp, hp']
          simpa
        case mpr =>
          intro hx
          rcases hx with ⟨w, hw, rfl⟩
          have : φ w ∈ closure e := by
            rw [←characteristic_map_range, Set.mem_range]
            use (congrArg (fun p ↦ (cb p : Type)) dim_e_eq_np1).mpr w
          use this
          have : Sum.inr (η w) ∈ S := hw
          use (skn_sum_cnp1_to_sknp1 n (Sum.inr (η w))), (by use (Sum.inr (η w)))
          simp [g₂, skn_sum_cnp1_to_sknp1, η, φ]
      rw [this]
      apply φ_closed_map
      exact IsClosed.preimage η_continuous (IsClosed.preimage continuous_inr SClosed)

end

section helper
variable {X: Type*} [TopologicalSpace X]
theorem aux_subspace_topology_eq {S: Set X} [TS: TopologicalSpace S] (h: ∀ (b: Set S), @IsClosed S TS b ↔ @IsClosed X _ ((↑) '' b)): TS = instTopologicalSpaceSubtype := by
  suffices ∀ (b:Set S), @IsClosed _ TS b ↔ @IsClosed _ instTopologicalSpaceSubtype b by
    ext s
    simp only [←isClosed_compl_iff, this]
  have S_closed : IsClosed S := by
    rw [←Subtype.coe_image_univ S, ←h]
    exact isClosed_univ
  intro b
  rw [h]
  refine Iff.intro ?mp ?mpr
  case mp =>
    intro hb
    use ((↑) '' b)ᶜ, hb.isOpen_compl
    simp
  case mpr =>
    intro hb
    exact S_closed.isClosedMap_subtype_val b hb
theorem is_closed_map_id : IsClosedMap (id: X → X) := by
  intro U UClosed
  simp [UClosed]
end helper

section
class CWComplexConstructor (X: Type*) where
  Fsk: ℕ → Set X
  Fsk0_nonempty: (Fsk 0).Nonempty
  Fsk_chain: ∀ n: ℕ, Fsk n ⊆ Fsk (n + 1)
  Fsk_cover: ⋃n:ℕ, Fsk n = Set.univ
  Tsk: (n:ℕ) → TopologicalSpace (Fsk n)  -- topology on skeletons
  Tsk0_discrete: DiscreteTopology (Fsk 0)
  Fι: ℕ → Type*   -- indexing type for gluing closed balls
  Ff: (n:ℕ) → {(x: Σ_:(Fι n), cb (n + 1)) | x.2 ∈ cb_boundary} → (Fsk n)  -- gluing function sending set of closed ball's boundary to skeleton n
  Ff_continuous: ∀ n, Continuous (Ff n)
  Fφ: (n:ℕ) → (AdjointSpace _ (Ff n)) → (Fsk (n + 1))
  Fφ_heomorph: ∀ n:ℕ, IsHomeomorph (Fφ n)
  Fφ_fix: ∀ n:ℕ, (Fφ n) ∘ (left_adj_proj _ (Ff n)) = fun x ↦ ⟨x.1,  (Fsk_chain n) x.2⟩

variable {X: Type*}
variable [CWC: CWComplexConstructor X]
instance {n:ℕ}: TopologicalSpace (CWC.Fsk n) := CWC.Tsk n

-- this topology is the same with what is defined by text
instance instCWConstructorTopology : TopologicalSpace X where
  IsOpen := fun s ↦ ∀ n:ℕ, IsOpen ((Subtype.val : (CWC.Fsk n) → X) ⁻¹' s)
  isOpen_univ := by simp
  isOpen_inter := by
    intro s t hs ht n
    rw [Set.preimage_inter]
    apply IsOpen.inter (hs n) (ht n)
  isOpen_sUnion := by
    intro ss hss n
    rw [Set.preimage_sUnion]
    apply isOpen_sUnion
    intro t ht
    simp at ht
    rcases ht with ⟨y, hy, rfl⟩
    apply isOpen_sUnion
    intro t ht
    simp at ht
    rcases ht with ⟨y', hy', rfl⟩
    apply hss y y'

theorem Fsk_incl {m n: ℕ} (hmn: m ≤ n) : CWC.Fsk m ⊆ CWC.Fsk n := by
  rcases Nat.exists_eq_add_of_le hmn with ⟨k, rfl⟩
  induction' k with k ik
  . simp
  trans (CWC.Fsk (m + k))
  . exact ik (Nat.le_add_right m k)
  rw [←add_assoc]
  apply CWC.Fsk_chain

lemma Fsk_chain_incl_continuous {n: ℕ}: Continuous ((fun x ↦ ⟨x.1, CWC.Fsk_chain _ x.2⟩): CWC.Fsk n → CWC.Fsk (n + 1)) := by
  rw [←CWC.Fφ_fix]
  refine Continuous.comp ?φ_cont ?left_adj_proj_cont
  case φ_cont => exact (CWC.Fφ_heomorph n).continuous
  case left_adj_proj_cont =>
    apply Topology.IsEmbedding.continuous
    refine left_adj_proj_is_embedding _ _ ?hAClosed (CWC.Ff_continuous n)
    rw [isClosed_sigma_iff]
    intro i
    simp [cb_boundary_closed]

theorem Fsk_incl_continuous {m n: ℕ} (hmn: m ≤ n): Continuous ((fun x ↦ ⟨x.1, Fsk_incl hmn x.2⟩): CWC.Fsk m → CWC.Fsk n) := by
  rcases Nat.exists_eq_add_of_le hmn with ⟨k, rfl⟩
  have aux: ∀ p q:ℕ, (h:p = q) → Continuous ((fun x ↦ ⟨x.1, Fsk_incl (Nat.le_of_eq h) x.2⟩):CWC.Fsk p → CWC.Fsk q) := by
    intro p q h
    exact @Eq.rec ℕ p (fun (p':ℕ) (eq:p=p') ↦ Continuous ((fun x ↦ ⟨x.1, Fsk_incl (Nat.le_of_eq eq) x.2⟩): CWC.Fsk p → CWC.Fsk p')) continuous_id q h
  induction' k with k ik
  . apply aux
    norm_num
  let f₁ : CWC.Fsk m → CWC.Fsk (m + k) := fun x ↦ ⟨x.1, Fsk_incl (Nat.le_add_right m k) x.2⟩
  let f₂ : CWC.Fsk (m + k) → CWC.Fsk (m + k + 1) := fun x ↦ ⟨x.1, CWC.Fsk_chain _ x.2⟩
  let f₃ : CWC.Fsk (m + k + 1) → CWC.Fsk (m + (k + 1)) := fun x ↦ ⟨x.1, Fsk_incl (Nat.le_of_eq (by rw[add_assoc])) x.2⟩
  let f : CWC.Fsk m → CWC.Fsk (m + (k + 1)) := fun x ↦ ⟨x.1, Fsk_incl hmn x.2⟩
  show Continuous f
  have: f = f₃ ∘ f₂ ∘ f₁ := by
    ext x
    simp [f, f₁, f₂, f₃]
  rw [this]
  have cont₁: Continuous f₁ := ik (Nat.le_add_right m k)
  have cont₂: Continuous f₂ := by apply Fsk_chain_incl_continuous
  have cont₃: Continuous f₃ := by
    apply aux
    rw [add_assoc]
  exact Continuous.comp cont₃ (Continuous.comp cont₂ cont₁)

lemma Fsk_chain_incl_closed_map {n:ℕ}: IsClosedMap ((fun x ↦ ⟨x.1, CWC.Fsk_chain _ x.2⟩): CWC.Fsk n → CWC.Fsk (n + 1)) := by
  rw [←CWC.Fφ_fix]
  refine IsClosedMap.comp ?φ_closed ?left_adj_proj_closed
  case φ_closed => exact (CWC.Fφ_heomorph n).isClosedMap
  case left_adj_proj_closed =>
    refine left_adj_proj_closed_map _ _ ?hAClosed (CWC.Ff_continuous n)
    rw [isClosed_sigma_iff]
    intro i
    simp [cb_boundary_closed]

theorem Fsk_incl_closed_map {m n: ℕ} (hmn: m ≤ n): IsClosedMap ((fun x ↦ ⟨x.1, Fsk_incl hmn x.2⟩): CWC.Fsk m → CWC.Fsk n) := by
  rcases Nat.exists_eq_add_of_le hmn with ⟨k, rfl⟩
  have aux: ∀ p q:ℕ, (h:p = q) → IsClosedMap ((fun x ↦ ⟨x.1, Fsk_incl (Nat.le_of_eq h) x.2⟩):CWC.Fsk p → CWC.Fsk q) := by
    intro p q h
    exact @Eq.rec ℕ p (fun (p':ℕ) (eq:p=p') ↦ IsClosedMap ((fun x ↦ ⟨x.1, Fsk_incl (Nat.le_of_eq eq) x.2⟩): CWC.Fsk p → CWC.Fsk p')) is_closed_map_id q h
  induction' k with k ik
  . apply aux
    simp
  let f₁ : CWC.Fsk m → CWC.Fsk (m + k) := fun x ↦ ⟨x.1, Fsk_incl (Nat.le_add_right m k) x.2⟩
  let f₂ : CWC.Fsk (m + k) → CWC.Fsk (m + k + 1) := fun x ↦ ⟨x.1, CWC.Fsk_chain _ x.2⟩
  let f₃ : CWC.Fsk (m + k + 1) → CWC.Fsk (m + (k + 1)) := fun x ↦ ⟨x.1, Fsk_incl (Nat.le_of_eq (by rw[add_assoc])) x.2⟩
  let f : CWC.Fsk m → CWC.Fsk (m + (k + 1)) := fun x ↦ ⟨x.1, Fsk_incl hmn x.2⟩
  show IsClosedMap f
  have: f = f₃ ∘ f₂ ∘ f₁ := by
    ext x
    simp [f, f₁, f₂, f₃]
  rw [this]
  have c₁: IsClosedMap f₁ := ik (Nat.le_add_right m k)
  have c₂: IsClosedMap f₂ := by apply Fsk_chain_incl_closed_map
  have c₃: IsClosedMap f₃ := by
    apply aux
    rw [add_assoc]
  exact IsClosedMap.comp c₃ (IsClosedMap.comp c₂ c₁)

lemma closed_in_cwc_iff {n: ℕ}: ∀ (b: Set (CWC.Fsk n)), IsClosed b ↔ IsClosed (((↑): CWC.Fsk n → X) '' b) := by
  intro b
  refine Iff.intro ?mp ?mpr
  case mp =>
    intro hb
    rw [←@isOpen_compl_iff]
    intro m
    show IsOpen ((((↑): CWC.Fsk m → X) ⁻¹' ((↑) '' b))ᶜ)
    rw [@isOpen_compl_iff]
    rcases Nat.le_total m n with m_le_n | n_le_m
    . let f : CWC.Fsk m → CWC.Fsk n := fun x ↦ ⟨x.1, Fsk_incl m_le_n x.2⟩
      have: ((↑): CWC.Fsk m → X) ⁻¹' (((↑): CWC.Fsk n → X) '' b) = f ⁻¹' b := by
        ext x
        simp [f]
        refine Iff.intro ?mp' ?mpr'
        case mp' =>
          rintro ⟨hx, x_in_b⟩
          exact x_in_b
        case mpr' =>
          intro x_in_b
          use Fsk_incl m_le_n x.2
      rw [this]
      exact IsClosed.preimage (Fsk_incl_continuous m_le_n) hb
    . let f : CWC.Fsk n → CWC.Fsk m := fun x ↦ ⟨x.1, Fsk_incl n_le_m x.2⟩
      have: ((↑): CWC.Fsk m → X) ⁻¹' (((↑): CWC.Fsk n → X) '' b) = f '' b := by
        ext x
        simp [f]
        refine Iff.intro ?mp' ?mpr'
        case mp' =>
          rintro ⟨x_in_skn, x_in_b⟩
          use x.1, x_in_skn
        case mpr' =>
          rintro ⟨x', ⟨x'_in_skn, x'_in_b, rfl⟩⟩
          use x'_in_skn
      rw [this]
      apply (Fsk_incl_closed_map n_le_m)
      exact hb
  case mpr =>
    intro b_closed_in_X
    rw [←@isOpen_compl_iff] at b_closed_in_X
    rw [←@isOpen_compl_iff]
    simpa using b_closed_in_X n

theorem Tsk_eq_subspace: ∀ n:ℕ, CWC.Tsk n = instTopologicalSpaceSubtype := by
  intro n
  apply aux_subspace_topology_eq
  apply closed_in_cwc_iff

theorem Fsk_closed: ∀ n:ℕ, IsClosed (CWC.Fsk n) := by
  intro n
  rw [←(Subtype.coe_image_univ (CWC.Fsk n)), ←closed_in_cwc_iff]
  exact isClosed_univ

theorem Fsk_coeherent: IsCoeherent (Set.range CWC.Fsk) := by
  refine { open_crit := ?_, cover := (by simpa using CWC.Fsk_cover)}
  simp
  intro s
  refine Iff.intro ?mp ?mpr
  case mp =>
    intro hs
    exact fun a ↦ IsOpen.preimage_val hs
  case mpr =>
    intro hs
    intro n
    have: @IsOpen _ (CWC.Tsk n) (((↑): CWC.Fsk n → X) ⁻¹' s) ↔ @IsOpen _ (instTopologicalSpaceSubtype) (((↑): CWC.Fsk n → X) ⁻¹' s) := by
      exact Eq.to_iff (congrFun (congrArg (@IsOpen (CWC.Fsk n)) (Tsk_eq_subspace n)) (((↑): CWC.Fsk n → X) ⁻¹' s))
    rw [this]
    exact hs n

namespace CWCellConstructor
def cell_of_dim0: Set (Set X) := {{x} | x ∈ CWC.Fsk 0}
-- using haskell pipe operator to ease expression of function composition
def pre_characteristic_map: (n: ℕ) → (Σ_:(CWC.Fι n), cb (n + 1)) → X :=
  fun n x ↦ Subtype.val <| (CWC.Fφ n) <| (adj_proj _ (CWC.Ff n)) <| Sum.inr x

def cell_define_map: (n:ℕ) → (CWC.Fι n) → b (n + 1) → X := fun n i x ↦ pre_characteristic_map n ⟨i, ⟨x.1, b_in_cb x.2⟩⟩

def cell_sets : Set (Set X) := {e | e ∈ cell_of_dim0 ∪ ⋃ n:ℕ, Set.range (fun (i: CWC.Fι n) ↦ Set.range <| cell_define_map n i) ∧ e.Nonempty}

theorem cell_sets_nonempty: ∀ e ∈ cell_sets (CWC := CWC), e.Nonempty := by
  intro e e_in_sets
  exact e_in_sets.2

lemma Fsk_n_cell_np1_disjoint: ∀ n:ℕ, ∀ i:(CWC.Fι n), Disjoint (CWC.Fsk n) (Set.range (cell_define_map n i)) := by
  intro n i
  let f : (CWC.Fsk (n + 1)) → X := (↑)
  have Xn_eq : CWC.Fsk n = f '' ((CWC.Fφ n) '' (Set.range (left_adj_proj _ (CWC.Ff n)))) := by
    rw [←Set.image_univ]
    nth_rw 2 [←Set.image_comp]
    rw [CWC.Fφ_fix, ←Set.image_comp]
    have : f ∘ (fun (x:CWC.Fsk n) ↦ ⟨x.1, (CWC.Fsk_chain n) x.2⟩) = Subtype.val := by
      ext x
      simp [f]
    rw [this]
    exact Eq.symm (Subtype.coe_image_univ (CWComplexConstructor.Fsk n))
  have cell_eq: Set.range (cell_define_map n i) ⊆ f '' ((CWC.Fφ n) '' (Set.range (right_adj_proj _ (CWC.Ff n)))) := by
    intro x hx
    simp [cell_define_map] at hx
    rcases hx with ⟨u, hu, u_maps_to_x⟩
    rw [pre_characteristic_map] at u_maps_to_x
    let v: cb (n + 1) := ⟨u, b_in_cb hu⟩
    have iv_not_in_boundary : ⟨i, v⟩ ∈ {x:Σ_:(CWC.Fι n), cb (n + 1) | x.2 ∈ cb_boundary}ᶜ := by
      simp [←cb_boundary_inner_cmpl]
      use ⟨u, hu⟩
      simp [v]
    let z := (right_adj_proj _ (CWC.Ff n)) ⟨⟨i, v⟩, iv_not_in_boundary⟩
    use (CWC.Fφ n) z
    constructor
    . use z
      simp [z]
    simp [←u_maps_to_x, f]
    rfl
  suffices Disjoint (f '' (((CWC.Fφ n) '' (Set.range (left_adj_proj _ (CWC.Ff n)))))) (f '' (((CWC.Fφ n)'' (Set.range (right_adj_proj _ (CWC.Ff n)))))) by
    rw [Xn_eq]
    exact Disjoint.symm (Set.disjoint_of_subset cell_eq (fun ⦃a⦄ a ↦ a) (id (Disjoint.symm this)))
  rw [Set.disjoint_image_iff Subtype.val_injective, Set.disjoint_image_iff (CWC.Fφ_heomorph n).injective]
  apply left_adj_right_adj_range_disjoint

lemma Fsk_0_cell_disjoint : ∀ n:ℕ, ∀ i:(CWC.Fι n), Disjoint (CWC.Fsk 0) (Set.range (cell_define_map n i)) := by
  intro n
  induction' n with n ih
  . apply Fsk_n_cell_np1_disjoint
  intro i
  apply Set.disjoint_of_subset (Fsk_incl (Nat.le_add_left 0 (n + 1))) (fun ⦃a⦄ a ↦ a)
  apply Fsk_n_cell_np1_disjoint

lemma cell0_sub_Fsk0: ∀ e ∈ cell_of_dim0, e ⊆ CWC.Fsk 0 := by
  rintro _ ⟨x, x_in_cd0, rfl⟩
  exact Set.singleton_subset_iff.mpr x_in_cd0

lemma cell_n_in_Fsk_np1: ∀ n:ℕ, ∀ i:(CWC.Fι n), (Set.range (cell_define_map n i)) ⊆ CWC.Fsk (n + 1) := by
  intro n i
  intro x hx
  simp [cell_define_map] at hx
  rcases hx with ⟨u, hu, u_maps_to_x⟩
  rw [pre_characteristic_map] at u_maps_to_x
  have: CWC.Fsk (n + 1) = Set.range (((↑): CWC.Fsk (n + 1) → X) ∘ (CWC.Fφ n)) := by
    rw [Set.range_comp, Set.range_eq_univ.mpr (CWC.Fφ_heomorph n).surjective]
    exact Eq.symm (Subtype.coe_image_univ (CWComplexConstructor.Fsk (n + 1)))
  rw [this, ←u_maps_to_x]
  simp

lemma cell_of_different_n_disjoint: ∀ n₁:ℕ, ∀ i₁:(CWC.Fι n₁), ∀ n₂:ℕ, ∀ i₂:(CWC.Fι n₂), n₁ ≠ n₂ → Disjoint (Set.range (cell_define_map n₁ i₁)) (Set.range (cell_define_map n₂ i₂)) := by
  intro n₁ i₁ n₂ i₂ n₁n₂_ne
  wlog n₁_lt_n₂:n₁ < n₂ generalizing n₁ i₁ n₂ i₂
  . have n₂_lt_n₁: n₂ < n₁ := by
      rcases Nat.lt_or_lt_of_ne n₁n₂_ne with h₁ | h₂
      . contradiction
      exact h₂
    apply Disjoint.symm
    exact this n₂ i₂ n₁ i₁ n₁n₂_ne.symm n₂_lt_n₁
  rcases Nat.exists_eq_add_of_le n₁_lt_n₂ with ⟨k, rfl⟩
  induction' k with k ih
  . apply Set.disjoint_of_subset (cell_n_in_Fsk_np1 n₁ i₁) (fun ⦃a⦄ a ↦ a)
    exact Fsk_n_cell_np1_disjoint (n₁ + 1) i₂
  have: Set.range (cell_define_map n₁ i₁) ⊆ CWC.Fsk (n₁.succ + (k + 1)) := by
    trans CWC.Fsk (n₁ + 1)
    . apply cell_n_in_Fsk_np1
    apply Fsk_incl
    exact n₁_lt_n₂
  apply Set.disjoint_of_subset (this) (fun ⦃a⦄ a ↦ a)
  apply Fsk_n_cell_np1_disjoint

lemma cell_of_same_n_different_i_disjoint: ∀ n:ℕ, ∀ (i₁ i₂:(CWC.Fι n)), i₁ ≠ i₂ → Disjoint (Set.range (cell_define_map n i₁)) (Set.range (cell_define_map n i₂)) := by
  intro n i₁ i₂ i₁_ne_i₂
  let A: (Set (Σ_:(CWC.Fι n), cb (n + 1))) := {x | x.2 ∈ cb_boundary}
  let B: (Set (Σ_:(CWC.Fι n), cb (n + 1))) := {x | x.2 ∈ cb_inner}
  have B_eq_A_compl: B = Aᶜ := by
    ext x
    refine Iff.intro ?mp ?mpr
    case mp =>
      intro x_in_B
      show x.2 ∈ cb_boundaryᶜ
      simp [←cb_boundary_inner_cmpl]
      exact x_in_B
    case mpr =>
      intro x_in_A
      have : x.2 ∈ cb_boundaryᶜ := x_in_A
      simp [←cb_boundary_inner_cmpl] at this
      exact this
  let f: (Aᶜ: (Set (Σ_:(CWC.Fι n), cb (n + 1))))→ X := fun x ↦ Subtype.val <| (CWC.Fφ n) <| (right_adj_proj _ (CWC.Ff n)) x
  let S: (CWC.Fι n) → (Set (Aᶜ: (Set (Σ_:(CWC.Fι n), cb (n + 1))))) := fun i ↦ {x | x.1.1 = i}
  have cell_rw: ∀ i:(CWC.Fι n), (Set.range (cell_define_map n i)) = f '' (S i) := by
    intro i
    ext x
    refine Iff.intro ?mp ?mpr
    case mp =>
      intro x_in_range
      rcases x_in_range with ⟨w, rfl⟩
      rw [cell_define_map, pre_characteristic_map]
      let u : (Σ_:(CWC.Fι n), cb (n + 1)) := ⟨i, ⟨w.1, b_in_cb w.2⟩⟩
      have u_in_A_compl : u ∈ Aᶜ := by
        rw [←B_eq_A_compl]
        use w
        rfl
      use ⟨u, u_in_A_compl⟩, rfl
      simp [f, u, right_adj_proj]
    case mpr =>
      intro x_in_fSi
      rcases x_in_fSi with ⟨w, w_in_S, rfl⟩
      have w'_in_B: w.1 ∈ B := by
        rw [B_eq_A_compl]
        exact w.2
      rcases w'_in_B with ⟨u, hu⟩
      have heq: w.1 = ⟨i, ⟨u,  b_in_cb u.2⟩ ⟩ := by
        exact Sigma.subtype_ext w_in_S (congrArg Subtype.val (id (Eq.symm hu)))
      use u
      simp [cell_define_map, pre_characteristic_map, f, right_adj_proj, heq]
  have f_inj: Function.Injective f := by
    apply Function.Injective.comp
    . exact Subtype.val_injective
    apply Function.Injective.comp
    . exact (CWC.Fφ_heomorph n).injective
    apply right_adj_proj_injective
  rw [cell_rw i₁, cell_rw i₂]
  refine (Set.disjoint_image_iff f_inj).mpr ?_
  refine Set.disjoint_iff_forall_ne.mpr ?_
  intro a ha b hb
  suffices a.1.1 ≠ b.1.1 by
    exact fun a_1 ↦ this (congrArg Sigma.fst (congrArg Subtype.val a_1))
  rw [ha, hb]
  exact i₁_ne_i₂

theorem cell_sets_disjoint: (cell_sets (CWC := CWC)).Pairwise Disjoint := by
  intro e₁ e₁_in_sets e₂ e₂_in_sets e₁_ne_e₂
  rcases e₁_in_sets with ⟨e₁_in_X0|e₁_in_Xn, e₁_nonempty⟩
  . rcases e₂_in_sets with ⟨e₂_in_X0|e₂_in_Xn, e₂_nonempty⟩
    . -- e₁ and e₂ are singleton
      rcases e₁_in_X0 with ⟨x₁, x₁_in_Fsk0, rfl⟩
      rcases e₂_in_X0 with ⟨x₂, x₂_in_Fsk0, rfl⟩
      -- generated by apply?
      exact Set.disjoint_singleton.mpr fun a ↦ e₁_ne_e₂ (congrArg singleton a)
    . simp at e₂_in_Xn
      rcases e₂_in_Xn with ⟨n, i, rfl⟩
      apply Set.disjoint_of_subset (cell0_sub_Fsk0 _ e₁_in_X0) (fun ⦃a⦄ a ↦ a)
      apply Fsk_0_cell_disjoint
  . simp at e₁_in_Xn
    rcases e₁_in_Xn with ⟨n₁, i₁, rfl⟩
    rcases e₂_in_sets with ⟨e₂_in_X0|e₂_in_Xn, e₂_nonempty⟩
    . apply Disjoint.symm
      apply Set.disjoint_of_subset (cell0_sub_Fsk0 _ e₂_in_X0) (fun ⦃a⦄ a ↦ a)
      apply Fsk_0_cell_disjoint
    . simp at e₂_in_Xn
      rcases e₂_in_Xn with ⟨n₂, i₂, rfl⟩
      rcases eq_or_ne n₁ n₂ with n₁_eq_n₂ | n₁_ne_n₂
      . have e₂_eq: Set.range (cell_define_map n₂ i₂) = Set.range (cell_define_map n₁ ((congrArg CWC.Fι n₁_eq_n₂).mpr i₂)) := by
          apply Eq.rec (motive := (fun n₂ eq ↦ ∀ i:(CWC.Fι n₂), Set.range (cell_define_map n₂ i) = Set.range (cell_define_map n₁ ((congrArg CWC.Fι eq).mpr i)))) (fun i ↦ rfl) n₁_eq_n₂
        rw [e₂_eq]
        have: i₁ ≠ ((congrArg CWC.Fι n₁_eq_n₂).mpr i₂) := by
          contrapose! e₁_ne_e₂
          rw [e₂_eq, e₁_ne_e₂]
        apply cell_of_same_n_different_i_disjoint
        exact this
      . apply cell_of_different_n_disjoint
        exact n₁_ne_n₂

lemma Fsk_cover' : ∀ x:X, ∃ n:ℕ, x ∈ CWC.Fsk n := by
  rw [←Set.iUnion_eq_univ_iff]
  exact CWC.Fsk_cover

lemma mem_cell_in_adj_sk {x: X} {n: ℕ} (x_not_in_Fsk_n: x ∉ CWC.Fsk n) (x_in_Fsk_np1: x ∈ CWC.Fsk (n + 1)) : ∃ (i:CWC.Fι n), x ∈ Set.range (cell_define_map n i) := by
  let y : (CWC.Fsk (n + 1)) := ⟨x, x_in_Fsk_np1⟩
  have y_coe_to_x: x = Subtype.val y := rfl
  rcases (CWC.Fφ_heomorph n).surjective y with ⟨w, w_maps_to_y⟩
  have w_in_right_range: w ∈ Set.range (right_adj_proj _ (CWC.Ff n)) := by
    rw [right_range_eq_left_range_compl]
    show w ∉ (Set.range (left_adj_proj _ (CWC.Ff n)))
    contrapose! x_not_in_Fsk_n
    rw [Set.mem_range] at x_not_in_Fsk_n
    rcases x_not_in_Fsk_n with ⟨x', x'_mapsto_w⟩
    have: (CWC.Fφ n) ((left_adj_proj _ (CWC.Ff n)) x') = ((CWC.Fφ n) ∘ (left_adj_proj _ (CWC.Ff n))) x' := rfl
    rw [←x'_mapsto_w, this, CWC.Fφ_fix, ←SetCoe.ext_iff] at w_maps_to_y
    simp at w_maps_to_y
    show y.1 ∈ CWC.Fsk n
    rw [←w_maps_to_y]
    exact x'.2
  rcases w_in_right_range with ⟨z, rfl⟩
  have : z.1.2 ∈ cb_inner := by rw [cb_inner_eq_boundary_compl]; exact z.2
  rcases this with ⟨q, q_is_z⟩
  use z.1.1, q
  have z_coe: ⟨z.1.1, ⟨q.1, b_in_cb q.2⟩⟩ = Subtype.val z := by
    have: Subtype.val z = ⟨z.1.1, z.1.2⟩ := rfl
    nth_rw 2 [this]
    apply congrArg (Sigma.mk z.1.1)
    rw [←q_is_z]
    rfl
  rw [cell_define_map, pre_characteristic_map, y_coe_to_x, Subtype.val_inj, ←w_maps_to_y, (CWC.Fφ_heomorph n).injective.eq_iff, z_coe]
  rfl

theorem cell_sets_cover: ⋃₀ (cell_sets (CWC := CWC)) = Set.univ := by
  rw [Set.sUnion_eq_univ_iff]
  intro x
  let Sn := {n:ℕ | x ∈ CWC.Fsk n}
  have Sn_nonempty:  Sn.Nonempty := by
    rcases Fsk_cover' x with ⟨n₀, hn₀⟩
    use n₀, hn₀
  let n := WellFounded.min wellFounded_lt Sn Sn_nonempty
  have x_in_Fskn : x ∈ CWC.Fsk n := WellFounded.min_mem wellFounded_lt Sn Sn_nonempty
  rcases Nat.eq_zero_or_pos n with n_eq_0 | n_gt_0
  . rw [n_eq_0] at x_in_Fskn
    use {x}
    simp [cell_sets, cell_of_dim0, x_in_Fskn]
  . have:  0 < n := n_gt_0
    rw [←Nat.exists_eq_add_one] at this
    rcases this with ⟨k, n_eq_k_succ⟩
    have k_lt_n: k < n := by linarith
    have x_not_in_Fsk_k : x ∉ CWC.Fsk k := by
      contrapose! k_lt_n
      apply WellFounded.min_le
      exact k_lt_n
    rw [n_eq_k_succ] at x_in_Fskn
    rcases mem_cell_in_adj_sk (CWC := CWC) x_not_in_Fsk_k x_in_Fskn with ⟨i, x_in_ki⟩
    use Set.range (cell_define_map k i)
    rw [and_comm]; use x_in_ki
    constructor
    . right
      rw [Set.mem_iUnion]
      use k
      simp
    use x

lemma exists_skn_contain_cell: ∀ e ∈ cell_sets, ∃ n, e ⊆ CWC.Fsk n := by
  intro e e_in_sets
  rcases e_in_sets with ⟨e_in_sk0 | e_in_skn, e_nonempty⟩
  . use 0
    apply cell0_sub_Fsk0 _ e_in_sk0
  . simp at e_in_skn
    rcases e_in_skn with ⟨n, ⟨i, rfl⟩⟩
    use (n + 1)
    exact cell_n_in_Fsk_np1 n i

lemma cell_of_dim0_in_sets: ∀ e ∈ cell_of_dim0, e ∈ cell_sets (CWC:=CWC) := by
  rintro e ⟨x, x_in_sk0, rfl⟩
  constructor
  . left
    use x
  . exact Set.singleton_nonempty x

lemma cell_define_map_range_in_sets: ∀ n, ∀ (i:CWC.Fι n), Set.range (cell_define_map n i) ∈ cell_sets := by
  intro n i
  constructor
  . right
    simp
    use n, i
  . exact Set.range_nonempty (cell_define_map n i)

noncomputable def dim_map : (cell_sets (CWC := CWC)) → ℕ := fun e ↦ WellFounded.min wellFounded_lt {n | e.1 ⊆ CWC.Fsk n} (by rcases exists_skn_contain_cell e.1 e.2 with ⟨n, hn ⟩; use n, hn)

lemma dim_map_cell_dim0_is_0 : ∀e, ∀ h:(e ∈ cell_of_dim0), dim_map ⟨e, cell_of_dim0_in_sets (CWC := CWC) e h⟩ = 0 := by
  rintro e ⟨x, x_in_sk0, e_is_x⟩
  suffices dim_map ⟨e, cell_of_dim0_in_sets e ⟨x, x_in_sk0, e_is_x⟩⟩ ≤ 0 by
    exact Nat.eq_zero_of_le_zero this
  apply WellFounded.min_le
  simp [←e_is_x, x_in_sk0]

lemma dim_map_cell_n_is_np1 : ∀ n:ℕ, ∀ (i: CWC.Fι n), dim_map ⟨Set.range (cell_define_map n i), cell_define_map_range_in_sets n i⟩ = (n + 1) := by
  intro n i
  let e : cell_sets := ⟨Set.range (cell_define_map n i), cell_define_map_range_in_sets n i⟩
  show dim_map e = n + 1
  have h_le: dim_map e ≤ n + 1 := by
    apply WellFounded.min_le
    apply cell_n_in_Fsk_np1
  have h_ge: dim_map e ≥ n + 1 := by
    by_contra! dim_map_e_lt_np1
    have dim_map_e_le_n: dim_map e ≤ n := Nat.le_of_lt_succ dim_map_e_lt_np1
    have e_in_skn: e.1 ⊆ CWC.Fsk n := by
      trans CWC.Fsk (dim_map e)
      . show dim_map e ∈ {n | e.1 ⊆ CWC.Fsk n}
        apply WellFounded.min_mem
      . exact Fsk_incl dim_map_e_le_n
    have e_eq_empty: e.1 = ∅ := Set.subset_empty_iff.mp ((Fsk_n_cell_np1_disjoint n i) e_in_skn (fun ⦃a⦄ a ↦ a))
    have e_ne_empty: e.1 ≠ ∅ := by
      rw [←Set.nonempty_iff_ne_empty]
      exact e.2.2
    contradiction
  linarith

lemma dim_map0_in_sk0: ∀ e:cell_sets, dim_map e = 0 → ∃ x:X, e.1 = {x} ∧ x ∈ CWC.Fsk 0 := by
  rintro ⟨e, e_in_sets⟩ dim_map_e_to_0
  rcases e_in_sets with ⟨e_in_cell0 | e_in_celln, e_non_empty⟩
  . rcases e_in_cell0 with ⟨x, x_in_sk0, rfl⟩
    use x
  . rw [Set.mem_iUnion] at e_in_celln
    rcases e_in_celln with ⟨n, ⟨i, e_eq⟩⟩
    simp at e_eq
    have e_sub_sk0: e ⊆ CWC.Fsk 0 := by
      show 0 ∈ {n | (⟨e, ⟨Or.inr e_in_celln, e_non_empty⟩⟩:cell_sets).1 ⊆ CWC.Fsk n}
      rw [←dim_map_e_to_0]
      apply WellFounded.min_mem
    have inter_empty: e ∩ CWC.Fsk 0 = ∅ := by
      rw [←Set.disjoint_iff_inter_eq_empty, ←e_eq, disjoint_comm]
      exact Fsk_0_cell_disjoint n i
    have inter_non_empty: e ∩ CWC.Fsk 0 ≠ ∅ := by
      rw [←Set.left_eq_inter] at e_sub_sk0
      rwa [←e_sub_sk0, ←Set.nonempty_iff_ne_empty]
    contradiction

def cell_sets₀ : Set (cell_sets (CWC:= CWC)) := {e | dim_map e = 0}

def cell_sets_indices := (CWC.Fsk 0) ⊕ (Σ(n:ℕ), CWC.Fι n)

def indices_to_Nat : (cell_sets_indices (CWC := CWC)) → ℕ := fun I ↦ match I with
| Sum.inl _ => 0
| Sum.inr ⟨n, _⟩ => n + 1

def indices_to_cb_to_X : (I: (cell_sets_indices (CWC := CWC))) → cb (indices_to_Nat (CWC := CWC) I) → X := fun I ↦ match I with
| Sum.inl ⟨x, _⟩ => fun _ ↦ x
| Sum.inr ⟨n, i⟩ => (Subtype.val) ∘ (CWC.Fφ n) ∘ (adj_proj _ (CWC.Ff n)) ∘ (@Sum.inr (CWC.Fsk n) _) ∘ (@Sigma.mk _ (fun _ ↦ cb (n + 1)) i)

def indices_to_cell: (cell_sets_indices (CWC := CWC)) → (cell_sets (CWC := CWC)) := fun I ↦ match I with
| Sum.inl ⟨x, x_in_sk0⟩ => ⟨{x}, ⟨by left; simp[cell_of_dim0, x_in_sk0] , Set.singleton_nonempty x ⟩⟩
| Sum.inr ⟨n, i⟩ => ⟨Set.range (cell_define_map n i), cell_define_map_range_in_sets n i⟩

lemma indices_to_cell_lr_ne (n: ℕ) (i: CWC.Fι n) (x: X) (hx: x ∈ CWC.Fsk 0) : indices_to_cell (Sum.inl ⟨x, hx⟩) ≠ indices_to_cell (Sum.inr ⟨n, i⟩) := by
  by_contra heq
  simp [indices_to_cell] at heq
  have : {x} ⊆ CWC.Fsk 0 := Set.singleton_subset_iff.mpr hx
  rw [heq] at this
  have: Set.range (cell_define_map n i) ≤ ⊥ := Fsk_0_cell_disjoint n i this (fun ⦃a⦄ a ↦ a)
  have eq_empty: Set.range (cell_define_map n i) = ∅ := Set.subset_eq_empty this rfl
  have ne_empty: Set.range (cell_define_map n i) ≠ ∅ := by
        rw [←Set.nonempty_iff_ne_empty]
        exact Set.range_nonempty (cell_define_map n i)
  contradiction

theorem indices_to_cell_injective: Function.Injective (indices_to_cell (CWC := CWC)):= by
  intro I1 I2 I1_I2_img_eq
  match I1 with
  | Sum.inl ⟨x₁, x₁_in_sk0⟩ =>
    match I2 with
    | Sum.inl ⟨x₂, x₂_in_sk0⟩ =>
      simp [indices_to_cell] at I1_I2_img_eq
      apply congrArg
      exact SetCoe.ext I1_I2_img_eq
    | Sum.inr ⟨n₂, i₂⟩ =>
      apply False.elim ((indices_to_cell_lr_ne n₂ i₂ x₁ x₁_in_sk0) I1_I2_img_eq)
  | Sum.inr ⟨n₁, i₁⟩ =>
    match I2 with
    | Sum.inl ⟨x₂, x₂_in_sk0⟩ =>
      apply False.elim ((indices_to_cell_lr_ne n₁ i₁ x₂ x₂_in_sk0) I1_I2_img_eq.symm)
    | Sum.inr ⟨n₂, i₂⟩ =>
      simp [indices_to_cell] at I1_I2_img_eq
      have n₁_n₂_eq: n₁ = n₂ := by
        by_contra! n₁_ne_n₂
        have hd: Disjoint (Set.range (cell_define_map n₁ i₁)) (Set.range (cell_define_map n₂ i₂)) := cell_of_different_n_disjoint n₁ i₁ n₂ i₂ n₁_ne_n₂
        rw [I1_I2_img_eq, Set.disjoint_iff_inter_eq_empty, Set.inter_self] at hd
        have h_nonempty: (Set.range (cell_define_map n₂ i₂)) ≠ ∅  := by
          rw [←Set.nonempty_iff_ne_empty]
          exact Set.range_nonempty (cell_define_map n₂ i₂)
        contradiction
      have: (⟨n₁, i₁⟩: Σn:ℕ, CWC.Fι n) = ⟨n₂, (congrArg CWC.Fι n₁_n₂_eq).mp i₁⟩ := by
        refine Sigma.mk.inj_iff.mpr ⟨n₁_n₂_eq, ?_⟩
        exact heq_of_eqRec_eq (congrArg (CWComplexConstructor.Fι X) n₁_n₂_eq) rfl
      rw [this]
      have range_rw: Set.range (cell_define_map n₁ i₁) = Set.range (cell_define_map n₂ ((congrArg CWC.Fι n₁_n₂_eq).mp i₁)) := by
        exact @Eq.rec ℕ n₁ (fun m n₁_eq_m ↦ Set.range (cell_define_map n₁ i₁) = Set.range (cell_define_map m ((congrArg CWC.Fι n₁_eq_m).mp i₁))) rfl n₂ n₁_n₂_eq
      rw [range_rw] at I1_I2_img_eq
      suffices (congrArg CWC.Fι n₁_n₂_eq).mp i₁ = i₂ by congr
      let i₁' := (congrArg CWC.Fι n₁_n₂_eq).mp i₁
      show i₁' = i₂
      by_contra! i₁'_ne_i₂
      have hd : Disjoint (Set.range (cell_define_map n₂ i₁')) (Set.range (cell_define_map n₂ i₂)) := cell_of_same_n_different_i_disjoint n₂ i₁' i₂ i₁'_ne_i₂
      rw [I1_I2_img_eq, Set.disjoint_iff_inter_eq_empty, Set.inter_self] at hd
      have h_nonempty: Set.range (cell_define_map n₂ i₂) ≠ ∅ := by
        rw [←Set.nonempty_iff_ne_empty]
        exact Set.range_nonempty (cell_define_map n₂ i₂)
      contradiction

theorem indices_to_cell_surjective : Function.Surjective (indices_to_cell (CWC := CWC)) := by
  rintro ⟨e, e_in_sets⟩
  rcases e_in_sets with ⟨e_in_sk0|e_in_skn, e_nonempty⟩
  . rcases e_in_sk0 with ⟨x, x_in_sk0, rfl⟩
    use Sum.inl ⟨x, x_in_sk0⟩
    rfl
  . rw [Set.mem_iUnion] at e_in_skn
    rcases e_in_skn with ⟨n, ⟨i, range_eq⟩⟩
    simp at range_eq
    use Sum.inr ⟨n, i⟩
    simp [indices_to_cell, range_eq]

instance cell_sets_indices_nonempty: Nonempty (cell_sets_indices (CWC := CWC)) := by
  rcases CWC.Fsk0_nonempty with ⟨x, x_in_sk0⟩
  use Sum.inl ⟨x, x_in_sk0 ⟩

noncomputable def cell_to_indices: (cell_sets (CWC := CWC)) → (cell_sets_indices (CWC := CWC)) := Function.invFun indices_to_cell

theorem cell_to_indices_left_inv: cell_to_indices ∘ (indices_to_cell (CWC := CWC))= id := by
  rw [cell_to_indices]
  refine Function.invFun_comp ?_
  exact indices_to_cell_injective

lemma cell_to_indices_left_inv': ∀ I, cell_to_indices (indices_to_cell (CWC := CWC) I) = I := by
  intro I
  show (cell_to_indices ∘ indices_to_cell) I = I
  rw [cell_to_indices_left_inv]
  rfl

theorem cell_to_indices_right_inv: (indices_to_cell (CWC := CWC)) ∘ cell_to_indices = id := by
  funext x
  simp [cell_to_indices]
  apply Function.invFun_eq
  revert x
  exact indices_to_cell_surjective

theorem dim_map_indices_to_nat_comm : ∀ e: (cell_sets (CWC := CWC)), indices_to_Nat (cell_to_indices e) = dim_map e := by
  rintro ⟨e, e_in_sets⟩
  rcases e_in_sets with ⟨e_in_sk0|e_in_skn, e_nonempty⟩
  . rw [dim_map_cell_dim0_is_0 e e_in_sk0]
    rcases e_in_sk0 with ⟨x, x_in_sk0, e_eq⟩
    have: ⟨e, ⟨Or.inl (Exists.intro x ⟨x_in_sk0, e_eq⟩), e_nonempty⟩⟩ = indices_to_cell (Sum.inl ⟨x, x_in_sk0⟩) := by simp [indices_to_cell, ←e_eq]
    simp [this, cell_to_indices_left_inv', indices_to_Nat]
  . rw [Set.mem_iUnion] at e_in_skn
    rcases e_in_skn with ⟨n, i, rfl⟩
    simp
    rw [dim_map_cell_n_is_np1]
    have : ⟨Set.range (cell_define_map n i), ⟨Or.inr e_in_skn, e_nonempty ⟩⟩ = indices_to_cell (Sum.inr ⟨n, i⟩) := by simp [indices_to_cell]
    simp [this, cell_to_indices_left_inv', indices_to_Nat]

noncomputable def characteristic_map : (e : (cell_sets (CWC := CWC))) → cb (dim_map e) → X := fun e ↦ (indices_to_cb_to_X (cell_to_indices e)) ∘ (congrArg (fun n ↦ (cb n:Type)) (dim_map_indices_to_nat_comm e).symm).mp

end CWCellConstructor
end
end Chp5
