import MyProject.TopologicalProperties

open BigOperators
namespace Chp5
open CellComplexClass

section
variable {X: Type*} [T: TopologicalSpace X] [T2Space X] [C: CellComplexClass X] [CW: CWComplexClass X]
-- a direct proof of 5.17
theorem quotient_sigma_cb_map : Topology.IsQuotientMap (fun (⟨e, d⟩: (_:C.sets) × cb (C.dim_map _)) ↦ C.characteristic_map e d) where
  surjective := by
    intro x
    simp
    rcases exists_mem_of_cell x with ⟨e, e_in_sets, x_in_e⟩
    use e, e_in_sets
    have : x ∈ Set.range (C.characteristic_map ⟨e, e_in_sets⟩) := by
      rw [characteristic_map_range]
      apply subset_closure
      exact x_in_e
    rw [Set.mem_range] at this
    rcases this with ⟨y, hy⟩
    use y.1, y.2
  eq_coinduced := by
    rw [TopologicalSpace.ext_iff]
    intro s
    let φ := fun (⟨e, d⟩: (_:C.sets) × cb (C.dim_map _)) ↦ C.characteristic_map e d
    show @IsOpen X T s ↔ @IsOpen X (TopologicalSpace.coinduced φ instTopologicalSpaceSigma) s
    have : @IsOpen X (TopologicalSpace.coinduced φ instTopologicalSpaceSigma) s ↔ IsOpen (φ ⁻¹' s) := by rfl
    rw [this, isOpen_sigma_iff]
    simp only [Set.preimage_preimage, φ]
    refine Iff.intro ?mp ?mpr
    case mp =>
      intro s_open_in_X e
      apply Continuous.isOpen_preimage ?_ s s_open_in_X
      exact characteristic_map_continuous e
    case mpr=>
      intro h
      rw [CW.coeherent.open_crit]
      rintro _ ⟨e, e_in_sets, rfl⟩
      let f : cb (C.dim_map ⟨e, e_in_sets⟩) → (closure e) := by
        intro d
        use C.characteristic_map ⟨e, e_in_sets⟩ d
        show characteristic_map ⟨e, e_in_sets⟩ d ∈ closure (⟨e, e_in_sets⟩:C.sets).1
        rw [←characteristic_map_range]
        exact Set.mem_range_self d
      let g : (closure e) → X := (↑)
      have f_cont: Continuous f := by
        -- this refine is generated by apply?
        refine
          Continuous.subtype_mk ?_ fun x ↦
            id
              (Eq.mpr
                (id
                  (congrArg (fun _a ↦ characteristic_map ⟨e, e_in_sets⟩ x ∈ _a)
                    (Eq.symm (characteristic_map_range ⟨e, e_in_sets⟩))))
                (Set.mem_range_self x))
        exact characteristic_map_continuous ⟨e, e_in_sets⟩
      have : Topology.IsQuotientMap f := by
        apply IsClosedMap.isQuotientMap (Continuous.isClosedMap f_cont) f_cont
        rintro ⟨x, x_in_ce⟩
        simp [f]
        rw [←characteristic_map_range' e e_in_sets, Set.mem_range] at x_in_ce
        rcases x_in_ce with ⟨y, hy⟩
        use y.1, y.2
      rw [←Topology.IsQuotientMap.isOpen_preimage this]
      rw [Set.preimage_preimage]
      apply h
end

section
variable {X Y Z: Type*} [TopologicalSpace X] [TopologicalSpace Y] [TopologicalSpace Z]
end

end Chp5
